//##### DZAP COMMON CONFIG ##############
//  DZE_COLOR_<TYPE> = [_percentRed,_percentBlue,_percentGreen,_percentOpaque]; colors used in addons
DZE_COLOR_PRIMARY = [(51/255),(181/255),(229/255),1];
DZE_COLOR_SUCCESS = [(153/255),(204/255),0,1];
DZE_COLOR_DANGER  = [1,(68/255),(68/255),1];
DZE_COLOR_WARNING = [1,(187/255),(51/255),1];
// DZE_COLOR_<TYPE>_HEX -- the hex color code string (including #) used in addons
DZE_COLOR_PRIMARY_HEX = "#33b5e5";
DZE_COLOR_SUCCESS_HEX = "#99cc00";
DZE_COLOR_DANGER_HEX  = "#ff4444";
DZE_COLOR_WARNING_HEX = "#ffbb33";

//##### CLICK ACTIONS CONFIGURATION #####
//  DZE_DEPLOYABLES_ENABLE - If true, click actions addon is enabled. If false, click actions addon is disabled.
DZE_CLICK_ACTIONS_ENABLE = true;
//  DZE_CLICK_ACTIONS parameters
//
//  parameter    | description                                                         |  type  | example
// --------------|---------------------------------------------------------------------|--------|--------
// _classname    | the name of the class to click on                                   | string | "ItemBloodbag"
// _text         | the text for the option that is displayed when right clicking       | string | "Self Transfusion"
// _execute      | uncompiled code to execute when the option is selected              | string | "execVM 'my\scripts\self_transfuse.sqf';"
// _condition    | uncompiled code to check whether the option should be displayed     | string | "true"
//
DZE_CLICK_ACTIONS = [
    ["ItemGPS","Scan Nearby","if(isNil 'DZE_CLICK_ACTIONS_GPS_RANGE') then {DZE_CLICK_ACTIONS_GPS_RANGE = 1000;};DZE_CLICK_ACTIONS_ZOMBIE_COUNT = count ((position player) nearEntities ['zZombie_Base',DZE_CLICK_ACTIONS_GPS_RANGE]); DZE_CLICK_ACTIONS_MAN_COUNT = count ((position player) nearEntities ['CAManBase',DZE_CLICK_ACTIONS_GPS_RANGE]);cutText[format['Within %1 Meters: %2 AI/players, %3 zombies, %4 vehicles',DZE_CLICK_ACTIONS_GPS_RANGE,DZE_CLICK_ACTIONS_MAN_COUNT - DZE_CLICK_ACTIONS_ZOMBIE_COUNT,count ((position player) nearEntities ['zZombie_Base',DZE_CLICK_ACTIONS_GPS_RANGE]),count ((position player) nearEntities ['allVehicles',DZE_CLICK_ACTIONS_GPS_RANGE]) - DZE_CLICK_ACTIONS_MAN_COUNT],'PLAIN DOWN'];","true"],
    ["ItemGPS","Range Up"   ,"if(isNil 'DZE_CLICK_ACTIONS_GPS_RANGE') then {DZE_CLICK_ACTIONS_GPS_RANGE = 1000;};DZE_CLICK_ACTIONS_GPS_RANGE = (DZE_CLICK_ACTIONS_GPS_RANGE + 100) min 1500; cutText[format['GPS RANGE: %1',DZE_CLICK_ACTIONS_GPS_RANGE],'PLAIN DOWN'];","true"],
    ["ItemGPS","Range Down" ,"if(isNil 'DZE_CLICK_ACTIONS_GPS_RANGE') then {DZE_CLICK_ACTIONS_GPS_RANGE = 1000;};DZE_CLICK_ACTIONS_GPS_RANGE = (DZE_CLICK_ACTIONS_GPS_RANGE - 100) max 500;  cutText[format['GPS RANGE: %1',DZE_CLICK_ACTIONS_GPS_RANGE],'PLAIN DOWN'];","true"],
	["ItemBriefcase_Base","Open Mystery Briefcase","execVM 'custom\addons\mbc\open_brief.sqf'","true"],
	["ItemKnife","Harvest weed","execVM 'custom\addons\weed\harvest.sqf';","true"]
];

//##### DEPLOYABLE VEHICLES AND BUILDINGS CONFIGURATION ##########################################################################################################################################################
//  DZE_DEPLOYABLES_ENABLE - If true, deployable addon is enabled. If false, deployable addon is disabled. REQUIRES DZE_CLICK_ACTIONS_ENABLE = true;
DZE_DEPLOYABLES_ENABLE = true;
//  DZE_DEPLOYABLES_CONFIG parameters
//
//  parameter    | description                                                         |  type  | example
// --------------|---------------------------------------------------------------------|--------|--------
// _clickItem    | class name of the item to click on                                  | string | "ItemToolbox"
// _deployOffset | [_side,_front,_up] array to offset the deployable when buiding      | array  | [0,2,1]
// _packDistance | how close does the packer need to be to pack the object?            | number | 5
// _damageLimit  | item can't be repacked if damage is > this. (-1 = no re-packing)    | number | 0.1
// _packAny      | can anyone repack the deployable?                                   | bool   | false
// _cargo        | clear the cargo of the deployable?                                  | bool   | false
// _hive         | write deployable to database?                                       | bool   | false
// _plot         | require a plot from the owner to build the deployable?              | bool   | false
// _simulation   | enable simulation (movement/damage) for the object? (true for cars) | bool   | true
// _road         | enable road building for this object?                               | bool   | true
// _deployables  | array of class names that can be deployed with this method          | array  | ["MMT_Civ"]
// _near         | array of items required nearby to build (workshop/fire/fueltank)    | array  | []
// _parts        | array of parts required to build (will be taken from player)        | array  | ["ItemToolbox"]
// _reqRank		 | Required Rank to build this item									   | number | 1-10
DZE_DEPLOYABLES_CONFIG = [
    // deploy a non-permanent bike from a toolbox right in front of the player that can be re-packed by the owner as long as it's under 10% damage
	// deploy a non-permanent ATV from a toolbox, engine parts and fuel tank right in front of the player that can be re-packed by the owner as long as it's under 10% damage
	["ItemToolbox",[0,2,1],5,0.1,false,false,false,false,true,true,["MMT_Civ"],[],["ItemToolbox"],1],
	["ItemToolbox",[0,2,2],5,0.1,false,false,false,false,true,true,["ATV_US_EP1"],[],["ItemToolbox"],3],
    ["ItemToolbox",[0,5,2],7,0.1,false,false,false,false,true,true,["CSJ_GyroC"],[],["ItemToolbox"],5]
];
//  DZE_DEPLOYABLE_NAME_MAP parameters
//
//  parameter    | description                                                         |  type  | example
// --------------|---------------------------------------------------------------------|--------|--------
// _class        | class name of the item you want to replace the name of              | string | "Notebook"
// _name         | new name to display when right clicking                             | string | "Macbook Pro"
//
DZE_DEPLOYABLE_NAME_MAP = [
    ["Notebook","Macbook Pro"]
];
//  DZE_DEPLOYABLE_ADMINS = [_adminPlayerUID1, _adminPlayerUID2, ...more...];
DZE_DEPLOYABLE_ADMINS = ["76561198173462307"];

//##### WEAPON MODIFICATION CONFIGURATION #########################################################################################################################################################################
//  DZE_WEAPON_MOD_ENABLE - If true, weapon mod addon is enabled. If false, weapon mod addon is disabled. REQUIRES DZE_CLICK_ACTIONS_ENABLE = true;
DZE_WEAPON_MOD_ENABLE = true;
//  DZE_WEAPON_MOD_ADMINS = [_adminPlayerUID1, _adminPlayerUID2, ...more...];
DZE_WEAPON_MOD_ADMINS = ["76561198173462307"];
//  DZE_WEAPON_MOD_INV_CHECK_ITEMS = [_checkItem1,_checkItem2, ...more...];
DZE_WEAPON_MOD_INV_CHECK_ITEMS = ["ItemToolbox"];
//  DZE_WEAPON_MOD_USE_HINT_INVENTORY -- If true, the hint system will be used to track inventory. If false, a message with the inventory will be displayed in chat.
DZE_WEAPON_MOD_USE_HINT_INVENTORY = true;
//  DZE_WEAPON_MODS parameters
//
//   parameter    | description                                                         |  type  | example
//  --------------|---------------------------------------------------------------------|--------|--------
//  _attachment   | the name of the weapon attachment                                   | string | "GP25 GL"
//  _base         | the classname that the attachment is put on to                      | string | "AK_74"
//  _upgrade      | the classname the item becomes after the attachment it put on       | string | "AK_74_GL"
//
DZE_WEAPON_MODS = [
    ["GP25 GL"      ,"AK_74"                ,"AK_74_GL"             ],
    ["Kobra Sight"  ,"AK_74_GL"             ,"AK_74_GL_kobra"       ],
    ["Stock"        ,"AK_47_S"              ,"AK_47_M"              ],
    ["GP25 GL"      ,"AK_107_kobra"         ,"AK_107_GL_kobra"      ],
    ["PSO Scope"    ,"AK_107_kobra"         ,"AK_107_pso"           ],
    ["GP25 GL"      ,"AK_107_pso"           ,"AK_107_GL_pso"        ],
    ["PSO Scope"    ,"AK_107_GL_kobra"      ,"AK_107_GL_pso"        ],
    ["Gold Paint"   ,"AKS_74"               ,"AKS_GOLD"             ],
    ["Kobra Sight"  ,"AKS_74"               ,"AKS_74_kobra"         ],
    ["Suppressor"   ,"AKS_74_kobra"         ,"AKS_74_UN_kobra"      ],
    ["PSO Scope"    ,"AKS_74"               ,"AKS_74_pso"           ],
    ["NV Scope"     ,"AKS_74"               ,"AKS_74_NSPU"          ],
    ["Thermal Scope","AKS_74"               ,"AKS_74_GOSHAWK"       ],
    ["Thermal Scope","BAF_AS50_scoped"   	,"BAF_AS50_TWS"         ],
	["Thermal Scope","BAF_AS50_scoped_DZ"   ,"BAF_AS50_TWS"         ],
	["Thermal Scope","PMC_AS50_scoped"   	,"PMC_AS50_TWS"         ],
    ["M203 GL"      ,"BAF_L85A2_RIS_Holo"   ,"BAF_L85A2_UGL_Holo"   ],
    ["SUSAT Sight"  ,"BAF_L85A2_RIS_Holo"   ,"BAF_L85A2_RIS_SUSAT"  ],
    ["M203 GL"      ,"BAF_L85A2_RIS_SUSAT"  ,"BAF_L85A2_UGL_SUSAT"  ],
    ["SUSAT Sight"  ,"BAF_L85A2_UGL_Holo"   ,"BAF_L85A2_UGL_SUSAT"  ],
    ["ACOG Scope"   ,"BAF_L85A2_RIS_Holo"   ,"BAF_L85A2_RIS_ACOG"   ],
    ["M203 GL"      ,"BAF_L85A2_RIS_ACOG"   ,"BAF_L85A2_UGL_ACOG"   ],
    ["ACOG Scope"   ,"BAF_L85A2_UGL_Holo"   ,"BAF_L85A2_UGL_ACOG"   ],
    ["Thermal Scope","BAF_L85A2_RIS_Holo"   ,"BAF_L85A2_RIS_CWS"    ],
    ["Suppressor"   ,"bizon"                ,"bizon_silenced"       ],
	["Camo Paint"   ,"FHQ_ACR_BLK_IRN"   	,"FHQ_ACR_WDL_IRN"   	],
	["Camo Paint"   ,"FHQ_ACR_BLK_IRN_GL"  	,"FHQ_ACR_WDL_IRN_GL"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_IRN_SD"  	,"FHQ_ACR_WDL_IRN_SD"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_IRN_GL_SD","FHQ_ACR_WDL_IRN_GL_SD"],
	["Camo Paint"   ,"FHQ_ACR_BLK_IRN_F"   	  ,"FHQ_ACR_WDL_IRN_F"   	],
	["Camo Paint"   ,"FHQ_ACR_BLK_IRN_GL_F"   ,"FHQ_ACR_WDL_IRN_GL_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_IRN_SD_F"   ,"FHQ_ACR_WDL_IRN_SD_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_IRN_GL_SD_F","FHQ_ACR_WDL_IRN_GL_SD_F"],
	["Camo Paint"   ,"FHQ_ACR_BLK_RCO"  	,"FHQ_ACR_WDL_RCO"],
	["Camo Paint"   ,"FHQ_ACR_BLK_RCO_GL"  	,"FHQ_ACR_WDL_RCO_GL"],
	["Camo Paint"   ,"FHQ_ACR_BLK_RCO_SD"  	,"FHQ_ACR_WDL_RCO_SD"],
	["Camo Paint"   ,"FHQ_ACR_BLK_RCO_GL_SD","FHQ_ACR_WDL_RCO_GL_SD"],
	["Camo Paint"   ,"FHQ_ACR_BLK_RCO_F"   	  ,"FHQ_ACR_WDL_RCO_F"   	],
	["Camo Paint"   ,"FHQ_ACR_BLK_RCO_GL_F"   ,"FHQ_ACR_WDL_RCO_GL_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_RCO_SD_F"   ,"FHQ_ACR_WDL_RCO_SD_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_RCO_GL_SD_F","FHQ_ACR_WDL_RCO_GL_SD_F"],	
	["Camo Paint" 	,"FHQ_ACR_BLK_CCO"  	,"FHQ_ACR_WDL_CCO"],
	["Camo Paint" 	,"FHQ_ACR_BLK_CCO_GL"  	,"FHQ_ACR_WDL_CCO_GL"],
	["Camo Paint" 	,"FHQ_ACR_BLK_CCO_SD"  	,"FHQ_ACR_WDL_CCO_SD"],
	["Camo Paint" 	,"FHQ_ACR_BLK_CCO_GL_SD","FHQ_ACR_WDL_CCO_GL_SD"],
	["Camo Paint"   ,"FHQ_ACR_BLK_CCO_F"   	  ,"FHQ_ACR_WDL_CCO_F"   	],
	["Camo Paint"   ,"FHQ_ACR_BLK_CCO_GL_F"   ,"FHQ_ACR_WDL_CCO_GL_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_CCO_SD_F"   ,"FHQ_ACR_WDL_CCO_SD_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_CCO_GL_SD_F","FHQ_ACR_WDL_CCO_GL_SD_F"],	
	["Camo Paint" 	,"FHQ_ACR_BLK_G55"  	,"FHQ_ACR_WDL_G55"],
	["Camo Paint" 	,"FHQ_ACR_BLK_G55_GL"  	,"FHQ_ACR_WDL_G55_GL"],
	["Camo Paint" 	,"FHQ_ACR_BLK_G55_SD"  	,"FHQ_ACR_WDL_G55_SD"],
	["Camo Paint" 	,"FHQ_ACR_BLK_G55_GL_SD","FHQ_ACR_WDL_G55_GL_SD"],
	["Camo Paint"   ,"FHQ_ACR_BLK_G55_F"   	  ,"FHQ_ACR_WDL_G55_F"   	],
	["Camo Paint"   ,"FHQ_ACR_BLK_G55_GL_F"   ,"FHQ_ACR_WDL_G55_GL_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_G55_SD_F"   ,"FHQ_ACR_WDL_G55_SD_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_G55_GL_SD_F","FHQ_ACR_WDL_G55_GL_SD_F"],
	["Camo Paint" 	,"FHQ_ACR_BLK_HAMR"  	,"FHQ_ACR_WDL_HAMR"],
	["Camo Paint" 	,"FHQ_ACR_BLK_HAMR_GL"  ,"FHQ_ACR_WDL_HAMR_GL"],
	["Camo Paint" 	,"FHQ_ACR_BLK_HAMR_SD"  ,"FHQ_ACR_WDL_HAMR_SD"],
	["Camo Paint" 	,"FHQ_ACR_BLK_HAMR_GL_SD","FHQ_ACR_WDL_HAMR_GL_SD"],
	["Camo Paint"   ,"FHQ_ACR_BLK_HAMR_F"      ,"FHQ_ACR_WDL_HAMR_F"   	  ],
	["Camo Paint"   ,"FHQ_ACR_BLK_HAMR_GL_F"   ,"FHQ_ACR_WDL_HAMR_GL_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_HAMR_SD_F"   ,"FHQ_ACR_WDL_HAMR_SD_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_HAMR_GL_SD_F","FHQ_ACR_WDL_HAMR_GL_SD_F"],	
	["Camo Paint" 	,"FHQ_ACR_BLK_HWS"  	,"FHQ_ACR_WDL_HWS"],
	["Camo Paint" 	,"FHQ_ACR_BLK_HWS_GL"  	,"FHQ_ACR_WDL_HWS_GL"],
	["Camo Paint" 	,"FHQ_ACR_BLK_HWS_SD"  	,"FHQ_ACR_WDL_HWS_SD"],
	["Camo Paint" 	,"FHQ_ACR_BLK_HWS_GL_SD","FHQ_ACR_WDL_HWS_GL_SD"],
	["Camo Paint"   ,"FHQ_ACR_BLK_HWS_F"      ,"FHQ_ACR_WDL_HWS_F"   	],
	["Camo Paint"   ,"FHQ_ACR_BLK_HWS_GL_F"   ,"FHQ_ACR_WDL_HWS_GL_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_HWS_SD_F"   ,"FHQ_ACR_WDL_HWS_SD_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_HWS_GL_SD_F","FHQ_ACR_WDL_HWS_GL_SD_F"],	
	["Camo Paint"	,"FHQ_ACR_BLK_TWS"  	,"FHQ_ACR_WDL_TWS"],
	["Camo Paint"	,"FHQ_ACR_BLK_TWS_GL"  	,"FHQ_ACR_WDL_TWS_GL"],
	["Camo Paint"	,"FHQ_ACR_BLK_TWS_SD"  	,"FHQ_ACR_WDL_TWS_SD"],
	["Camo Paint"	,"FHQ_ACR_BLK_TWS_GL_SD","FHQ_ACR_WDL_TWS_GL_SD"],
	["Camo Paint"   ,"FHQ_ACR_BLK_TWS_F"      ,"FHQ_ACR_WDL_TWS_F"   	],
	["Camo Paint"   ,"FHQ_ACR_BLK_TWS_GL_F"   ,"FHQ_ACR_WDL_TWS_GL_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_TWS_SD_F"   ,"FHQ_ACR_WDL_TWS_SD_F"   ],
	["Camo Paint"   ,"FHQ_ACR_BLK_TWS_GL_SD_F","FHQ_ACR_WDL_TWS_GL_SD_F"],	
	["Desert Paint" ,"FHQ_ACR_BLK_IRN"   	,"FHQ_ACR_TAN_IRN"   	],
	["Desert Paint" ,"FHQ_ACR_BLK_IRN_GL"  	,"FHQ_ACR_TAN_IRN_GL"   ],
	["Desert Paint" ,"FHQ_ACR_BLK_IRN_SD"  	,"FHQ_ACR_TAN_IRN_SD"   ],
	["Desert Paint" ,"FHQ_ACR_BLK_IRN_GL_SD","FHQ_ACR_TAN_IRN_GL_SD"],	
	["Desert Paint" ,"FHQ_ACR_BLK_IRN_F"   	  ,"FHQ_ACR_TAN_IRN_F"   	],
	["Desert Paint" ,"FHQ_ACR_BLK_IRN_GL_F"   ,"FHQ_ACR_TAN_IRN_GL_F"   ],
	["Desert Paint" ,"FHQ_ACR_BLK_IRN_SD_F"   ,"FHQ_ACR_TAN_IRN_SD_F"   ],
	["Desert Paint" ,"FHQ_ACR_BLK_IRN_GL_SD_F","FHQ_ACR_TAN_IRN_GL_SD_F"],
	["Desert Paint" ,"FHQ_ACR_BLK_RCO"  	,"FHQ_ACR_TAN_RCO"],
	["Desert Paint" ,"FHQ_ACR_BLK_RCO_GL"  	,"FHQ_ACR_TAN_RCO_GL"],
	["Desert Paint" ,"FHQ_ACR_BLK_RCO_SD"  	,"FHQ_ACR_TAN_RCO_SD"],
	["Desert Paint" ,"FHQ_ACR_BLK_RCO_GL_SD","FHQ_ACR_TAN_RCO_GL_SD"],
	["Desert Paint" ,"FHQ_ACR_BLK_RCO_F"   	  ,"FHQ_ACR_TAN_RCO_F"   	],
	["Desert Paint" ,"FHQ_ACR_BLK_RCO_GL_F"   ,"FHQ_ACR_TAN_RCO_GL_F"   ],
	["Desert Paint" ,"FHQ_ACR_BLK_RCO_SD_F"   ,"FHQ_ACR_TAN_RCO_SD_F"   ],
	["Desert Paint" ,"FHQ_ACR_BLK_RCO_GL_SD_F","FHQ_ACR_TAN_RCO_GL_SD_F"],	
	["Desert Paint" ,"FHQ_ACR_BLK_CCO"  	,"FHQ_ACR_TAN_CCO"],
	["Desert Paint" 	,"FHQ_ACR_BLK_CCO_GL"  	,"FHQ_ACR_TAN_CCO_GL"],
	["Desert Paint" 	,"FHQ_ACR_BLK_CCO_SD"  	,"FHQ_ACR_TAN_CCO_SD"],
	["Desert Paint" 	,"FHQ_ACR_BLK_CCO_GL_SD","FHQ_ACR_TAN_CCO_GL_SD"],
	["Desert Paint"   ,"FHQ_ACR_BLK_CCO_F"   	  ,"FHQ_ACR_TAN_CCO_F"   	],
	["Desert Paint"   ,"FHQ_ACR_BLK_CCO_GL_F"   ,"FHQ_ACR_TAN_CCO_GL_F"   ],
	["Desert Paint"   ,"FHQ_ACR_BLK_CCO_SD_F"   ,"FHQ_ACR_TAN_CCO_SD_F"   ],
	["Desert Paint"   ,"FHQ_ACR_BLK_CCO_GL_SD_F","FHQ_ACR_TAN_CCO_GL_SD_F"],	
	["Desert Paint" 	,"FHQ_ACR_BLK_G55"  	,"FHQ_ACR_TAN_G55"],
	["Desert Paint" 	,"FHQ_ACR_BLK_G55_GL"  	,"FHQ_ACR_TAN_G55_GL"],
	["Desert Paint" 	,"FHQ_ACR_BLK_G55_SD"  	,"FHQ_ACR_TAN_G55_SD"],
	["Desert Paint" 	,"FHQ_ACR_BLK_G55_GL_SD","FHQ_ACR_TAN_G55_GL_SD"],
	["Desert Paint"   ,"FHQ_ACR_BLK_G55_F"   	  ,"FHQ_ACR_TAN_G55_F"   	],
	["Desert Paint"   ,"FHQ_ACR_BLK_G55_GL_F"   ,"FHQ_ACR_TAN_G55_GL_F"   ],
	["Desert Paint"   ,"FHQ_ACR_BLK_G55_SD_F"   ,"FHQ_ACR_TAN_G55_SD_F"   ],
	["Desert Paint"   ,"FHQ_ACR_BLK_G55_GL_SD_F","FHQ_ACR_TAN_G55_GL_SD_F"],
	["Desert Paint" 	,"FHQ_ACR_BLK_HAMR"  	,"FHQ_ACR_TAN_HAMR"],
	["Desert Paint" 	,"FHQ_ACR_BLK_HAMR_GL"  ,"FHQ_ACR_TAN_HAMR_GL"],
	["Desert Paint" 	,"FHQ_ACR_BLK_HAMR_SD"  ,"FHQ_ACR_TAN_HAMR_SD"],
	["Desert Paint" 	,"FHQ_ACR_BLK_HAMR_GL_SD","FHQ_ACR_TAN_HAMR_GL_SD"],
	["Desert Paint"   ,"FHQ_ACR_BLK_HAMR_F"      ,"FHQ_ACR_TAN_HAMR_F"   	  ],
	["Desert Paint"   ,"FHQ_ACR_BLK_HAMR_GL_F"   ,"FHQ_ACR_TAN_HAMR_GL_F"   ],
	["Desert Paint"   ,"FHQ_ACR_BLK_HAMR_SD_F"   ,"FHQ_ACR_TAN_HAMR_SD_F"   ],
	["Desert Paint"   ,"FHQ_ACR_BLK_HAMR_GL_SD_F","FHQ_ACR_TAN_HAMR_GL_SD_F"],	
	["Desert Paint" 	,"FHQ_ACR_BLK_HWS"  	,"FHQ_ACR_TAN_HWS"],
	["Desert Paint" 	,"FHQ_ACR_BLK_HWS_GL"  	,"FHQ_ACR_TAN_HWS_GL"],
	["Desert Paint" 	,"FHQ_ACR_BLK_HWS_SD"  	,"FHQ_ACR_TAN_HWS_SD"],
	["Desert Paint" 	,"FHQ_ACR_BLK_HWS_GL_SD","FHQ_ACR_TAN_HWS_GL_SD"],
	["Desert Paint"   ,"FHQ_ACR_BLK_HWS_F"      ,"FHQ_ACR_TAN_HWS_F"   	],
	["Desert Paint"   ,"FHQ_ACR_BLK_HWS_GL_F"   ,"FHQ_ACR_TAN_HWS_GL_F"   ],
	["Desert Paint"   ,"FHQ_ACR_BLK_HWS_SD_F"   ,"FHQ_ACR_TAN_HWS_SD_F"   ],
	["Desert Paint"   ,"FHQ_ACR_BLK_HWS_GL_SD_F","FHQ_ACR_TAN_HWS_GL_SD_F"],	
	["Desert Paint"	,"FHQ_ACR_BLK_TWS"  	,"FHQ_ACR_TAN_TWS"],
	["Desert Paint"	,"FHQ_ACR_BLK_TWS_GL"  	,"FHQ_ACR_TAN_TWS_GL"],
	["Desert Paint"	,"FHQ_ACR_BLK_TWS_SD"  	,"FHQ_ACR_TAN_TWS_SD"],
	["Desert Paint"	,"FHQ_ACR_BLK_TWS_GL_SD","FHQ_ACR_TAN_TWS_GL_SD"],
	["Desert Paint"   ,"FHQ_ACR_BLK_TWS_F"      ,"FHQ_ACR_TAN_TWS_F"   	],
	["Desert Paint"   ,"FHQ_ACR_BLK_TWS_GL_F"   ,"FHQ_ACR_TAN_TWS_GL_F"   ],
	["Desert Paint"   ,"FHQ_ACR_BLK_TWS_SD_F"   ,"FHQ_ACR_TAN_TWS_SD_F"   ],
	["Desert Paint"   ,"FHQ_ACR_BLK_TWS_GL_SD_F","FHQ_ACR_TAN_TWS_GL_SD_F"],	
	["Winter Paint" ,"FHQ_ACR_BLK_IRN"   	,"FHQ_ACR_SNW_IRN"   	],
	["Winter Paint" ,"FHQ_ACR_BLK_IRN_GL"  	,"FHQ_ACR_SNW_IRN_GL"   ],
	["Winter Paint" ,"FHQ_ACR_BLK_IRN_SD"  	,"FHQ_ACR_SNW_IRN_SD"   ],
	["Winter Paint" ,"FHQ_ACR_BLK_IRN_GL_SD","FHQ_ACR_SNW_IRN_GL_SD"],
	["Winter Paint" ,"FHQ_ACR_BLK_IRN_F"   	  ,"FHQ_ACR_SNW_IRN_F"   	],
	["Winter Paint" ,"FHQ_ACR_BLK_IRN_GL_F"   ,"FHQ_ACR_SNW_IRN_GL_F"   ],
	["Winter Paint" ,"FHQ_ACR_BLK_IRN_SD_F"   ,"FHQ_ACR_SNW_IRN_SD_F"   ],
	["Winter Paint" ,"FHQ_ACR_BLK_IRN_GL_SD_F","FHQ_ACR_SNW_IRN_GL_SD_F"],
	["Winter Paint"   ,"FHQ_ACR_BLK_RCO"  	,"FHQ_ACR_SNW_RCO"],
	["Winter Paint"   ,"FHQ_ACR_BLK_RCO_GL"  	,"FHQ_ACR_SNW_RCO_GL"],
	["Winter Paint"   ,"FHQ_ACR_BLK_RCO_SD"  	,"FHQ_ACR_SNW_RCO_SD"],
	["Winter Paint"   ,"FHQ_ACR_BLK_RCO_GL_SD","FHQ_ACR_SNW_RCO_GL_SD"],
	["Winter Paint"   ,"FHQ_ACR_BLK_RCO_F"   	  ,"FHQ_ACR_SNW_RCO_F"   	],
	["Winter Paint"   ,"FHQ_ACR_BLK_RCO_GL_F"   ,"FHQ_ACR_SNW_RCO_GL_F"   ],
	["Winter Paint"   ,"FHQ_ACR_BLK_RCO_SD_F"   ,"FHQ_ACR_SNW_RCO_SD_F"   ],
	["Winter Paint"   ,"FHQ_ACR_BLK_RCO_GL_SD_F","FHQ_ACR_SNW_RCO_GL_SD_F"],	
	["Winter Paint" 	,"FHQ_ACR_BLK_CCO"  	,"FHQ_ACR_SNW_CCO"],
	["Winter Paint" 	,"FHQ_ACR_BLK_CCO_GL"  	,"FHQ_ACR_SNW_CCO_GL"],
	["Winter Paint" 	,"FHQ_ACR_BLK_CCO_SD"  	,"FHQ_ACR_SNW_CCO_SD"],
	["Winter Paint" 	,"FHQ_ACR_BLK_CCO_GL_SD","FHQ_ACR_SNW_CCO_GL_SD"],
	["Winter Paint"   ,"FHQ_ACR_BLK_CCO_F"   	  ,"FHQ_ACR_SNW_CCO_F"   	],
	["Winter Paint"   ,"FHQ_ACR_BLK_CCO_GL_F"   ,"FHQ_ACR_SNW_CCO_GL_F"   ],
	["Winter Paint"   ,"FHQ_ACR_BLK_CCO_SD_F"   ,"FHQ_ACR_SNW_CCO_SD_F"   ],
	["Winter Paint"   ,"FHQ_ACR_BLK_CCO_GL_SD_F","FHQ_ACR_SNW_CCO_GL_SD_F"],	
	["Winter Paint" 	,"FHQ_ACR_BLK_G55"  	,"FHQ_ACR_SNW_G55"],
	["Winter Paint" 	,"FHQ_ACR_BLK_G55_GL"  	,"FHQ_ACR_SNW_G55_GL"],
	["Winter Paint" 	,"FHQ_ACR_BLK_G55_SD"  	,"FHQ_ACR_SNW_G55_SD"],
	["Winter Paint" 	,"FHQ_ACR_BLK_G55_GL_SD","FHQ_ACR_SNW_G55_GL_SD"],
	["Winter Paint"   ,"FHQ_ACR_BLK_G55_F"   	  ,"FHQ_ACR_SNW_G55_F"   	],
	["Winter Paint"   ,"FHQ_ACR_BLK_G55_GL_F"   ,"FHQ_ACR_SNW_G55_GL_F"   ],
	["Winter Paint"   ,"FHQ_ACR_BLK_G55_SD_F"   ,"FHQ_ACR_SNW_G55_SD_F"   ],
	["Winter Paint"   ,"FHQ_ACR_BLK_G55_GL_SD_F","FHQ_ACR_SNW_G55_GL_SD_F"],
	["Winter Paint" 	,"FHQ_ACR_BLK_HAMR"  	,"FHQ_ACR_SNW_HAMR"],
	["Winter Paint" 	,"FHQ_ACR_BLK_HAMR_GL"  ,"FHQ_ACR_SNW_HAMR_GL"],
	["Winter Paint" 	,"FHQ_ACR_BLK_HAMR_SD"  ,"FHQ_ACR_SNW_HAMR_SD"],
	["Winter Paint" 	,"FHQ_ACR_BLK_HAMR_GL_SD","FHQ_ACR_SNW_HAMR_GL_SD"],
	["Winter Paint"   ,"FHQ_ACR_BLK_HAMR_F"      ,"FHQ_ACR_SNW_HAMR_F"   	  ],
	["Winter Paint"   ,"FHQ_ACR_BLK_HAMR_GL_F"   ,"FHQ_ACR_SNW_HAMR_GL_F"   ],
	["Winter Paint"   ,"FHQ_ACR_BLK_HAMR_SD_F"   ,"FHQ_ACR_SNW_HAMR_SD_F"   ],
	["Winter Paint"   ,"FHQ_ACR_BLK_HAMR_GL_SD_F","FHQ_ACR_SNW_HAMR_GL_SD_F"],	
	["Winter Paint" 	,"FHQ_ACR_BLK_HWS"  	,"FHQ_ACR_SNW_HWS"],
	["Winter Paint" 	,"FHQ_ACR_BLK_HWS_GL"  	,"FHQ_ACR_SNW_HWS_GL"],
	["Winter Paint" 	,"FHQ_ACR_BLK_HWS_SD"  	,"FHQ_ACR_SNW_HWS_SD"],
	["Winter Paint" 	,"FHQ_ACR_BLK_HWS_GL_SD","FHQ_ACR_SNW_HWS_GL_SD"],
	["Winter Paint"   ,"FHQ_ACR_BLK_HWS_F"      ,"FHQ_ACR_SNW_HWS_F"   	],
	["Winter Paint"   ,"FHQ_ACR_BLK_HWS_GL_F"   ,"FHQ_ACR_SNW_HWS_GL_F"   ],
	["Winter Paint"   ,"FHQ_ACR_BLK_HWS_SD_F"   ,"FHQ_ACR_SNW_HWS_SD_F"   ],
	["Winter Paint"   ,"FHQ_ACR_BLK_HWS_GL_SD_F","FHQ_ACR_SNW_HWS_GL_SD_F"],	
	["Winter Paint"	,"FHQ_ACR_BLK_TWS"  	,"FHQ_ACR_TAN_SNW"],
	["Winter Paint"	,"FHQ_ACR_BLK_TWS_GL"  	,"FHQ_ACR_TAN_SNW_GL"],
	["Winter Paint"	,"FHQ_ACR_BLK_TWS_SD"  	,"FHQ_ACR_TAN_SNW_SD"],
	["Winter Paint"	,"FHQ_ACR_BLK_TWS_GL_SD","FHQ_ACR_TAN_SNW_GL_SD"],
	["Winter Paint"   ,"FHQ_ACR_BLK_TWS_F"      ,"FHQ_ACR_TAN_SNW_F"   	],
	["Winter Paint"   ,"FHQ_ACR_BLK_TWS_GL_F"   ,"FHQ_ACR_TAN_SNW_GL_F"   ],
	["Winter Paint"   ,"FHQ_ACR_BLK_TWS_SD_F"   ,"FHQ_ACR_TAN_SNW_SD_F"   ],
	["Winter Paint"   ,"FHQ_ACR_BLK_TWS_GL_SD_F","FHQ_ACR_TAN_SNW_GL_SD_F"],	
	["M320 GL"      ,"FHQ_ACR_BLK_IRN"   	,"FHQ_ACR_BLK_IRN_GL"   ],
	["Suppressor"   ,"FHQ_ACR_BLK_IRN"   	,"FHQ_ACR_BLK_IRN_SD"   ],
	["M320 GL"   	,"FHQ_ACR_BLK_IRN_SD"  	,"FHQ_ACR_BLK_IRN_GL_SD"],
	["M320 GL"      ,"FHQ_ACR_BLK_IRN_F"   	,"FHQ_ACR_BLK_IRN_GL_F"   ],
	["Suppressor"   ,"FHQ_ACR_BLK_IRN_F"   	,"FHQ_ACR_BLK_IRN_SD_F"   ],
	["M320 GL"   	,"FHQ_ACR_BLK_IRN_SD_F" ,"FHQ_ACR_BLK_IRN_GL_SD_F"],
	["ACOG Scope"   ,"FHQ_ACR_BLK_IRN"  	,"FHQ_ACR_BLK_RCO"],
	["ACOG Scope"   ,"FHQ_ACR_BLK_IRN_GL"  	,"FHQ_ACR_BLK_RCO_GL"],
	["ACOG Scope"   ,"FHQ_ACR_BLK_IRN_SD"  	,"FHQ_ACR_BLK_RCO_SD"],
	["ACOG Scope"   ,"FHQ_ACR_BLK_IRN_GL_SD","FHQ_ACR_BLK_RCO_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_BLK_RCO"  	,"FHQ_ACR_BLK_RCO_GL"],
	["Suppressor"   ,"FHQ_ACR_BLK_RCO"  	,"FHQ_ACR_BLK_RCO_SD"],
	["M320 GL"   	,"FHQ_ACR_BLK_RCO_SD"  	,"FHQ_ACR_BLK_RCO_GL_SD"],
	["ACOG Scope"   ,"FHQ_ACR_BLK_IRN_F"  	,"FHQ_ACR_BLK_RCO_F"],
	["ACOG Scope"   ,"FHQ_ACR_BLK_IRN_GL_F" ,"FHQ_ACR_BLK_RCO_GL_F"],
	["ACOG Scope"   ,"FHQ_ACR_BLK_IRN_SD_F" ,"FHQ_ACR_BLK_RCO_SD_F"],
	["ACOG Scope"   ,"FHQ_ACR_BLK_IRN_GL_SD_F","FHQ_ACR_BLK_RCO_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_BLK_RCO_F"  	,"FHQ_ACR_BLK_RCO_GL_F"],
	["Suppressor"   ,"FHQ_ACR_BLK_RCO_F"  	,"FHQ_ACR_BLK_RCO_SD_F"],
	["M320 GL"   	,"FHQ_ACR_BLK_RCO_SD_F" ,"FHQ_ACR_BLK_RCO_GL_SD_F"],
	["CCO Scope" ,"FHQ_ACR_BLK_IRN"  	,"FHQ_ACR_BLK_CCO"],
	["CCO Scope" ,"FHQ_ACR_BLK_IRN_GL"  	,"FHQ_ACR_BLK_CCO_GL"],
	["CCO Scope" ,"FHQ_ACR_BLK_IRN_SD"  	,"FHQ_ACR_BLK_CCO_SD"],
	["CCO Scope" ,"FHQ_ACR_BLK_IRN_GL_SD","FHQ_ACR_BLK_CCO_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_BLK_CCO"  	,"FHQ_ACR_BLK_CCO_GL"],
	["Suppressor"   ,"FHQ_ACR_BLK_CCO"  	,"FHQ_ACR_BLK_CCO_SD"],
	["M320 GL"   	,"FHQ_ACR_BLK_CCO_SD"  	,"FHQ_ACR_BLK_CCO_GL_SD"],
	["CCO Scope" ,"FHQ_ACR_BLK_IRN_F"  	,"FHQ_ACR_BLK_CCO_F"],
	["CCO Scope" ,"FHQ_ACR_BLK_IRN_GL_F" ,"FHQ_ACR_BLK_CCO_GL_F"],
	["CCO Scope" ,"FHQ_ACR_BLK_IRN_SD_F" ,"FHQ_ACR_BLK_CCO_SD_F"],
	["CCO Scope" ,"FHQ_ACR_BLK_IRN_GL_SD_F","FHQ_ACR_BLK_CCO_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_BLK_CCO_F"  	,"FHQ_ACR_BLK_CCO_GL_F"],
	["Suppressor"   ,"FHQ_ACR_BLK_CCO_F"  	,"FHQ_ACR_BLK_CCO_SD_F"],
	["M320 GL"   	,"FHQ_ACR_BLK_CCO_SD_F" ,"FHQ_ACR_BLK_CCO_GL_SD_F"],
	["G55 Scope" 	,"FHQ_ACR_BLK_IRN"  	,"FHQ_ACR_BLK_G55"],
	["G55 Scope" 	,"FHQ_ACR_BLK_IRN_GL"  	,"FHQ_ACR_BLK_G55_GL"],
	["G55 Scope" 	,"FHQ_ACR_BLK_IRN_SD"  	,"FHQ_ACR_BLK_G55_SD"],
	["G55 Scope" 	,"FHQ_ACR_BLK_IRN_GL_SD","FHQ_ACR_BLK_G55_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_BLK_G55"  	,"FHQ_ACR_BLK_G55_GL"],
	["Suppressor"   ,"FHQ_ACR_BLK_G55"  	,"FHQ_ACR_BLK_G55_SD"],
	["M320 GL"   	,"FHQ_ACR_BLK_G55_SD"  	,"FHQ_ACR_BLK_G55_GL_SD"],
	["G55 Scope" 	,"FHQ_ACR_BLK_IRN_F"  	,"FHQ_ACR_BLK_G55_F"],
	["G55 Scope" 	,"FHQ_ACR_BLK_IRN_GL_F" ,"FHQ_ACR_BLK_G55_GL_F"],
	["G55 Scope" 	,"FHQ_ACR_BLK_IRN_SD_F" ,"FHQ_ACR_BLK_G55_SD_F"],
	["G55 Scope" 	,"FHQ_ACR_BLK_IRN_GL_SD_F","FHQ_ACR_BLK_G55_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_BLK_G55_F"  	,"FHQ_ACR_BLK_G55_GL_F"],
	["Suppressor"   ,"FHQ_ACR_BLK_G55_F"  	,"FHQ_ACR_BLK_G55_SD_F"],
	["M320 GL"   	,"FHQ_ACR_BLK_G55_SD_F" ,"FHQ_ACR_BLK_G55_GL_SD_F"],
	["HAMR Scope" 	,"FHQ_ACR_BLK_IRN"  	,"FHQ_ACR_BLK_HAMR"],
	["HAMR Scope" 	,"FHQ_ACR_BLK_IRN_GL"  	,"FHQ_ACR_BLK_HAMR_GL"],
	["HAMR Scope" 	,"FHQ_ACR_BLK_IRN_SD"  	,"FHQ_ACR_BLK_HAMR_SD"],
	["HAMR Scope" 	,"FHQ_ACR_BLK_IRN_GL_SD","FHQ_ACR_BLK_HAMR_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_BLK_HAMR"  	,"FHQ_ACR_BLK_HAMR_GL"],
	["Suppressor"   ,"FHQ_ACR_BLK_HAMR"  	,"FHQ_ACR_BLK_HAMR_SD"],
	["M320 GL"   	,"FHQ_ACR_BLK_HAMR_SD"  ,"FHQ_ACR_BLK_HAMR_GL_SD"],
	["HAMR Scope" 	,"FHQ_ACR_BLK_IRN_F"  	,"FHQ_ACR_BLK_HAMR_F"],
	["HAMR Scope" 	,"FHQ_ACR_BLK_IRN_GL_F" ,"FHQ_ACR_BLK_HAMR_GL_F"],
	["HAMR Scope" 	,"FHQ_ACR_BLK_IRN_SD_F" ,"FHQ_ACR_BLK_HAMR_SD_F"],
	["HAMR Scope" 	,"FHQ_ACR_BLK_IRN_GL_SD_F","FHQ_ACR_BLK_HAMR_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_BLK_HAMR_F"  	,"FHQ_ACR_BLK_HAMR_GL_F"],
	["Suppressor"   ,"FHQ_ACR_BLK_HAMR_F"  	,"FHQ_ACR_BLK_HAMR_SD_F"],
	["M320 GL"   	,"FHQ_ACR_BLK_HAMR_SD_F","FHQ_ACR_BLK_HAMR_GL_SD_F"],
	["HWS Scope" 	,"FHQ_ACR_BLK_IRN"  	,"FHQ_ACR_BLK_HWS"],
	["HWS Scope" 	,"FHQ_ACR_BLK_IRN_GL"  	,"FHQ_ACR_BLK_HWS_GL"],
	["HWS Scope" 	,"FHQ_ACR_BLK_IRN_SD"  	,"FHQ_ACR_BLK_HWS_SD"],
	["HWS Scope" 	,"FHQ_ACR_BLK_IRN_GL_SD","FHQ_ACR_BLK_HWS_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_BLK_HWS"  	,"FHQ_ACR_BLK_HWS_GL"],
	["Suppressor"   ,"FHQ_ACR_BLK_HWS"  	,"FHQ_ACR_BLK_HWS_SD"],
	["M320 GL"   	,"FHQ_ACR_BLK_HWS_SD"   ,"FHQ_ACR_BLK_HWS_GL_SD"],
	["HWS Scope" 	,"FHQ_ACR_BLK_IRN_F"  	,"FHQ_ACR_BLK_HWS_F"],
	["HWS Scope" 	,"FHQ_ACR_BLK_IRN_GL_F" ,"FHQ_ACR_BLK_HWS_GL_F"],
	["HWS Scope" 	,"FHQ_ACR_BLK_IRN_SD_F" ,"FHQ_ACR_BLK_HWS_SD_F"],
	["HWS Scope" 	,"FHQ_ACR_BLK_IRN_GL_SD_F","FHQ_ACR_BLK_HWS_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_BLK_HWS_F"  	,"FHQ_ACR_BLK_HWS_GL_F"],
	["Suppressor"   ,"FHQ_ACR_BLK_HWS_F"  	,"FHQ_ACR_BLK_HWS_SD_F"],
	["M320 GL"   	,"FHQ_ACR_BLK_HWS_SD_F" ,"FHQ_ACR_BLK_HWS_GL_SD_F"],
	["Thermal Scope","FHQ_ACR_BLK_IRN"  	,"FHQ_ACR_BLK_TWS"],
	["Thermal Scope","FHQ_ACR_BLK_IRN_GL"  	,"FHQ_ACR_BLK_TWS_GL"],
	["Thermal Scope","FHQ_ACR_BLK_IRN_SD"  	,"FHQ_ACR_BLK_TWS_SD"],
	["Thermal Scope","FHQ_ACR_BLK_IRN_GL_SD","FHQ_ACR_BLK_TWS_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_BLK_TWS"  	,"FHQ_ACR_BLK_TWS_GL"],
	["Suppressor"   ,"FHQ_ACR_BLK_TWS"  	,"FHQ_ACR_BLK_TWS_SD"],
	["M320 GL"   	,"FHQ_ACR_BLK_TWS_SD"   ,"FHQ_ACR_BLK_TWS_GL_SD"],
	["Thermal Scope","FHQ_ACR_BLK_IRN_F"  	,"FHQ_ACR_BLK_TWS_F"],
	["Thermal Scope","FHQ_ACR_BLK_IRN_GL_F" ,"FHQ_ACR_BLK_TWS_GL_F"],
	["Thermal Scope","FHQ_ACR_BLK_IRN_SD_F" ,"FHQ_ACR_BLK_TWS_SD_F"],
	["Thermal Scope","FHQ_ACR_BLK_IRN_GL_SD_F","FHQ_ACR_BLK_TWS_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_BLK_TWS_F"  	,"FHQ_ACR_BLK_TWS_GL_F"],
	["Suppressor"   ,"FHQ_ACR_BLK_TWS_F"  	,"FHQ_ACR_BLK_TWS_SD_F"],
	["M320 GL"   	,"FHQ_ACR_BLK_TWS_SD_F" ,"FHQ_ACR_BLK_TWS_GL_SD_F"],
	["M320 GL"      ,"FHQ_ACR_WDL_IRN"   	,"FHQ_ACR_WDL_IRN_GL"   ],
	["Suppressor"   ,"FHQ_ACR_WDL_IRN"   	,"FHQ_ACR_WDL_IRN_SD"   ],
	["M320 GL"   	,"FHQ_ACR_WDL_IRN_SD"  	,"FHQ_ACR_WDL_IRN_GL_SD"],
	["M320 GL"      ,"FHQ_ACR_WDL_IRN_F"   	,"FHQ_ACR_WDL_IRN_GL_F"   ],
	["Suppressor"   ,"FHQ_ACR_WDL_IRN_F"   	,"FHQ_ACR_WDL_IRN_SD_F"   ],
	["M320 GL"   	,"FHQ_ACR_WDL_IRN_SD_F" ,"FHQ_ACR_WDL_IRN_GL_SD_F"],
	["ACOG Scope"   ,"FHQ_ACR_WDL_IRN"  	,"FHQ_ACR_WDL_RCO"],
	["ACOG Scope"   ,"FHQ_ACR_WDL_IRN_GL"  	,"FHQ_ACR_WDL_RCO_GL"],
	["ACOG Scope"   ,"FHQ_ACR_WDL_IRN_SD"  	,"FHQ_ACR_WDL_RCO_SD"],
	["ACOG Scope"   ,"FHQ_ACR_WDL_IRN_GL_SD","FHQ_ACR_WDL_RCO_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_WDL_RCO"  	,"FHQ_ACR_WDL_RCO_GL"],
	["Suppressor"   ,"FHQ_ACR_WDL_RCO"  	,"FHQ_ACR_WDL_RCO_SD"],
	["M320 GL"   	,"FHQ_ACR_WDL_RCO_SD"  	,"FHQ_ACR_WDL_RCO_GL_SD"],
	["ACOG Scope"   ,"FHQ_ACR_WDL_IRN_F"  	,"FHQ_ACR_WDL_RCO_F"],
	["ACOG Scope"   ,"FHQ_ACR_WDL_IRN_GL_F" ,"FHQ_ACR_WDL_RCO_GL_F"],
	["ACOG Scope"   ,"FHQ_ACR_WDL_IRN_SD_F" ,"FHQ_ACR_WDL_RCO_SD_F"],
	["ACOG Scope"   ,"FHQ_ACR_WDL_IRN_GL_SD_F","FHQ_ACR_WDL_RCO_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_WDL_RCO_F"  	,"FHQ_ACR_WDL_RCO_GL_F"],
	["Suppressor"   ,"FHQ_ACR_WDL_RCO_F"  	,"FHQ_ACR_WDL_RCO_SD_F"],
	["M320 GL"   	,"FHQ_ACR_WDL_RCO_SD_F" ,"FHQ_ACR_WDL_RCO_GL_SD_F"],
	["CCO Scope" ,"FHQ_ACR_WDL_IRN"  	,"FHQ_ACR_WDL_CCO"],
	["CCO Scope" ,"FHQ_ACR_WDL_IRN_GL"  	,"FHQ_ACR_WDL_CCO_GL"],
	["CCO Scope" ,"FHQ_ACR_WDL_IRN_SD"  	,"FHQ_ACR_WDL_CCO_SD"],
	["CCO Scope" ,"FHQ_ACR_WDL_IRN_GL_SD","FHQ_ACR_WDL_CCO_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_WDL_CCO"  	,"FHQ_ACR_WDL_CCO_GL"],
	["Suppressor"   ,"FHQ_ACR_WDL_CCO"  	,"FHQ_ACR_WDL_CCO_SD"],
	["M320 GL"   	,"FHQ_ACR_WDL_CCO_SD"  	,"FHQ_ACR_WDL_CCO_GL_SD"],
	["CCO Scope" ,"FHQ_ACR_WDL_IRN_F"  	,"FHQ_ACR_WDL_CCO_F"],
	["CCO Scope" ,"FHQ_ACR_WDL_IRN_GL_F" ,"FHQ_ACR_WDL_CCO_GL_F"],
	["CCO Scope" ,"FHQ_ACR_WDL_IRN_SD_F" ,"FHQ_ACR_WDL_CCO_SD_F"],
	["CCO Scope" ,"FHQ_ACR_WDL_IRN_GL_SD_F","FHQ_ACR_WDL_CCO_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_WDL_CCO_F"  	,"FHQ_ACR_WDL_CCO_GL_F"],
	["Suppressor"   ,"FHQ_ACR_WDL_CCO_F"  	,"FHQ_ACR_WDL_CCO_SD_F"],
	["M320 GL"   	,"FHQ_ACR_WDL_CCO_SD_F" ,"FHQ_ACR_WDL_CCO_GL_SD_F"],
	["G55 Scope" 	,"FHQ_ACR_WDL_IRN"  	,"FHQ_ACR_WDL_G55"],
	["G55 Scope" 	,"FHQ_ACR_WDL_IRN_GL"  	,"FHQ_ACR_WDL_G55_GL"],
	["G55 Scope" 	,"FHQ_ACR_WDL_IRN_SD"  	,"FHQ_ACR_WDL_G55_SD"],
	["G55 Scope" 	,"FHQ_ACR_WDL_IRN_GL_SD","FHQ_ACR_WDL_G55_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_WDL_G55"  	,"FHQ_ACR_WDL_G55_GL"],
	["Suppressor"   ,"FHQ_ACR_WDL_G55"  	,"FHQ_ACR_WDL_G55_SD"],
	["M320 GL"   	,"FHQ_ACR_WDL_G55_SD"  	,"FHQ_ACR_WDL_G55_GL_SD"],
	["G55 Scope" 	,"FHQ_ACR_WDL_IRN_F"  	,"FHQ_ACR_WDL_G55_F"],
	["G55 Scope" 	,"FHQ_ACR_WDL_IRN_GL_F" ,"FHQ_ACR_WDL_G55_GL_F"],
	["G55 Scope" 	,"FHQ_ACR_WDL_IRN_SD_F" ,"FHQ_ACR_WDL_G55_SD_F"],
	["G55 Scope" 	,"FHQ_ACR_WDL_IRN_GL_SD_F","FHQ_ACR_WDL_G55_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_WDL_G55_F"  	,"FHQ_ACR_WDL_G55_GL_F"],
	["Suppressor"   ,"FHQ_ACR_WDL_G55_F"  	,"FHQ_ACR_WDL_G55_SD_F"],
	["M320 GL"   	,"FHQ_ACR_WDL_G55_SD_F" ,"FHQ_ACR_WDL_G55_GL_SD_F"],
	["HAMR Scope" 	,"FHQ_ACR_WDL_IRN"  	,"FHQ_ACR_WDL_HAMR"],
	["HAMR Scope" 	,"FHQ_ACR_WDL_IRN_GL"  	,"FHQ_ACR_WDL_HAMR_GL"],
	["HAMR Scope" 	,"FHQ_ACR_WDL_IRN_SD"  	,"FHQ_ACR_WDL_HAMR_SD"],
	["HAMR Scope" 	,"FHQ_ACR_WDL_IRN_GL_SD","FHQ_ACR_WDL_HAMR_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_WDL_HAMR"  	,"FHQ_ACR_WDL_HAMR_GL"],
	["Suppressor"   ,"FHQ_ACR_WDL_HAMR"  	,"FHQ_ACR_WDL_HAMR_SD"],
	["M320 GL"   	,"FHQ_ACR_WDL_HAMR_SD"  ,"FHQ_ACR_WDL_HAMR_GL_SD"],
	["HAMR Scope" 	,"FHQ_ACR_WDL_IRN_F"  	,"FHQ_ACR_WDL_HAMR_F"],
	["HAMR Scope" 	,"FHQ_ACR_WDL_IRN_GL_F" ,"FHQ_ACR_WDL_HAMR_GL_F"],
	["HAMR Scope" 	,"FHQ_ACR_WDL_IRN_SD_F" ,"FHQ_ACR_WDL_HAMR_SD_F"],
	["HAMR Scope" 	,"FHQ_ACR_WDL_IRN_GL_SD_F","FHQ_ACR_WDL_HAMR_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_WDL_HAMR_F"  	,"FHQ_ACR_WDL_HAMR_GL_F"],
	["Suppressor"   ,"FHQ_ACR_WDL_HAMR_F"  	,"FHQ_ACR_WDL_HAMR_SD_F"],
	["M320 GL"   	,"FHQ_ACR_WDL_HAMR_SD_F","FHQ_ACR_WDL_HAMR_GL_SD_F"],
	["HWS Scope" 	,"FHQ_ACR_WDL_IRN"  	,"FHQ_ACR_WDL_HWS"],
	["HWS Scope" 	,"FHQ_ACR_WDL_IRN_GL"  	,"FHQ_ACR_WDL_HWS_GL"],
	["HWS Scope" 	,"FHQ_ACR_WDL_IRN_SD"  	,"FHQ_ACR_WDL_HWS_SD"],
	["HWS Scope" 	,"FHQ_ACR_WDL_IRN_GL_SD","FHQ_ACR_WDL_HWS_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_WDL_HWS"  	,"FHQ_ACR_WDL_HWS_GL"],
	["Suppressor"   ,"FHQ_ACR_WDL_HWS"  	,"FHQ_ACR_WDL_HWS_SD"],
	["M320 GL"   	,"FHQ_ACR_WDL_HWS_SD"   ,"FHQ_ACR_WDL_HWS_GL_SD"],
	["HWS Scope" 	,"FHQ_ACR_WDL_IRN_F"  	,"FHQ_ACR_WDL_HWS_F"],
	["HWS Scope" 	,"FHQ_ACR_WDL_IRN_GL_F" ,"FHQ_ACR_WDL_HWS_GL_F"],
	["HWS Scope" 	,"FHQ_ACR_WDL_IRN_SD_F" ,"FHQ_ACR_WDL_HWS_SD_F"],
	["HWS Scope" 	,"FHQ_ACR_WDL_IRN_GL_SD_F","FHQ_ACR_WDL_HWS_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_WDL_HWS_F"  	,"FHQ_ACR_WDL_HWS_GL_F"],
	["Suppressor"   ,"FHQ_ACR_WDL_HWS_F"  	,"FHQ_ACR_WDL_HWS_SD_F"],
	["M320 GL"   	,"FHQ_ACR_WDL_HWS_SD_F" ,"FHQ_ACR_WDL_HWS_GL_SD_F"],
	["Thermal Scope","FHQ_ACR_WDL_IRN"  	,"FHQ_ACR_WDL_TWS"],
	["Thermal Scope","FHQ_ACR_WDL_IRN_GL"  	,"FHQ_ACR_WDL_TWS_GL"],
	["Thermal Scope","FHQ_ACR_WDL_IRN_SD"  	,"FHQ_ACR_WDL_TWS_SD"],
	["Thermal Scope","FHQ_ACR_WDL_IRN_GL_SD","FHQ_ACR_WDL_TWS_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_WDL_TWS"  	,"FHQ_ACR_WDL_TWS_GL"],
	["Suppressor"   ,"FHQ_ACR_WDL_TWS"  	,"FHQ_ACR_WDL_TWS_SD"],
	["M320 GL"   	,"FHQ_ACR_WDL_TWS_SD"   ,"FHQ_ACR_WDL_TWS_GL_SD"],
	["Thermal Scope","FHQ_ACR_WDL_IRN_F"  	,"FHQ_ACR_WDL_TWS_F"],
	["Thermal Scope","FHQ_ACR_WDL_IRN_GL_F" ,"FHQ_ACR_WDL_TWS_GL_F"],
	["Thermal Scope","FHQ_ACR_WDL_IRN_SD_F" ,"FHQ_ACR_WDL_TWS_SD_F"],
	["Thermal Scope","FHQ_ACR_WDL_IRN_GL_SD_F","FHQ_ACR_WDL_TWS_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_WDL_TWS_F"  	,"FHQ_ACR_WDL_TWS_GL_F"],
	["Suppressor"   ,"FHQ_ACR_WDL_TWS_F"  	,"FHQ_ACR_WDL_TWS_SD_F"],
	["M320 GL"   	,"FHQ_ACR_WDL_TWS_SD_F" ,"FHQ_ACR_WDL_TWS_GL_SD_F"],
	["M320 GL"      ,"FHQ_ACR_TAN_IRN"   	,"FHQ_ACR_TAN_IRN_GL"   ],
	["Suppressor"   ,"FHQ_ACR_TAN_IRN"   	,"FHQ_ACR_TAN_IRN_SD"   ],
	["M320 GL"   	,"FHQ_ACR_TAN_IRN_SD"  	,"FHQ_ACR_TAN_IRN_GL_SD"],
	["M320 GL"      ,"FHQ_ACR_TAN_IRN_F"   	,"FHQ_ACR_TAN_IRN_GL_F"   ],
	["Suppressor"   ,"FHQ_ACR_TAN_IRN_F"   	,"FHQ_ACR_TAN_IRN_SD_F"   ],
	["M320 GL"   	,"FHQ_ACR_TAN_IRN_SD_F" ,"FHQ_ACR_TAN_IRN_GL_SD_F"],
	["ACOG Scope"   ,"FHQ_ACR_TAN_IRN"  	,"FHQ_ACR_TAN_RCO"],
	["ACOG Scope"   ,"FHQ_ACR_TAN_IRN_GL"  	,"FHQ_ACR_TAN_RCO_GL"],
	["ACOG Scope"   ,"FHQ_ACR_TAN_IRN_SD"  	,"FHQ_ACR_TAN_RCO_SD"],
	["ACOG Scope"   ,"FHQ_ACR_TAN_IRN_GL_SD","FHQ_ACR_TAN_RCO_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_TAN_RCO"  	,"FHQ_ACR_TAN_RCO_GL"],
	["Suppressor"   ,"FHQ_ACR_TAN_RCO"  	,"FHQ_ACR_TAN_RCO_SD"],
	["M320 GL"   	,"FHQ_ACR_TAN_RCO_SD"  	,"FHQ_ACR_TAN_RCO_GL_SD"],
	["ACOG Scope"   ,"FHQ_ACR_TAN_IRN_F"  	,"FHQ_ACR_TAN_RCO_F"],
	["ACOG Scope"   ,"FHQ_ACR_TAN_IRN_GL_F" ,"FHQ_ACR_TAN_RCO_GL_F"],
	["ACOG Scope"   ,"FHQ_ACR_TAN_IRN_SD_F" ,"FHQ_ACR_TAN_RCO_SD_F"],
	["ACOG Scope"   ,"FHQ_ACR_TAN_IRN_GL_SD_F","FHQ_ACR_TAN_RCO_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_TAN_RCO_F"  	,"FHQ_ACR_TAN_RCO_GL_F"],
	["Suppressor"   ,"FHQ_ACR_TAN_RCO_F"  	,"FHQ_ACR_TAN_RCO_SD_F"],
	["M320 GL"   	,"FHQ_ACR_TAN_RCO_SD_F" ,"FHQ_ACR_TAN_RCO_GL_SD_F"],
	["CCO Scope" ,"FHQ_ACR_TAN_IRN"  	,"FHQ_ACR_TAN_CCO"],
	["CCO Scope" ,"FHQ_ACR_TAN_IRN_GL"  	,"FHQ_ACR_TAN_CCO_GL"],
	["CCO Scope" ,"FHQ_ACR_TAN_IRN_SD"  	,"FHQ_ACR_TAN_CCO_SD"],
	["CCO Scope" ,"FHQ_ACR_TAN_IRN_GL_SD","FHQ_ACR_TAN_CCO_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_TAN_CCO"  	,"FHQ_ACR_TAN_CCO_GL"],
	["Suppressor"   ,"FHQ_ACR_TAN_CCO"  	,"FHQ_ACR_TAN_CCO_SD"],
	["M320 GL"   	,"FHQ_ACR_TAN_CCO_SD"  	,"FHQ_ACR_TAN_CCO_GL_SD"],
	["CCO Scope" ,"FHQ_ACR_TAN_IRN_F"  	,"FHQ_ACR_TAN_CCO_F"],
	["CCO Scope" ,"FHQ_ACR_TAN_IRN_GL_F" ,"FHQ_ACR_TAN_CCO_GL_F"],
	["CCO Scope" ,"FHQ_ACR_TAN_IRN_SD_F" ,"FHQ_ACR_TAN_CCO_SD_F"],
	["CCO Scope" ,"FHQ_ACR_TAN_IRN_GL_SD_F","FHQ_ACR_TAN_CCO_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_TAN_CCO_F"  	,"FHQ_ACR_TAN_CCO_GL_F"],
	["Suppressor"   ,"FHQ_ACR_TAN_CCO_F"  	,"FHQ_ACR_TAN_CCO_SD_F"],
	["M320 GL"   	,"FHQ_ACR_TAN_CCO_SD_F" ,"FHQ_ACR_TAN_CCO_GL_SD_F"],
	["G55 Scope" 	,"FHQ_ACR_TAN_IRN"  	,"FHQ_ACR_TAN_G55"],
	["G55 Scope" 	,"FHQ_ACR_TAN_IRN_GL"  	,"FHQ_ACR_TAN_G55_GL"],
	["G55 Scope" 	,"FHQ_ACR_TAN_IRN_SD"  	,"FHQ_ACR_TAN_G55_SD"],
	["G55 Scope" 	,"FHQ_ACR_TAN_IRN_GL_SD","FHQ_ACR_TAN_G55_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_TAN_G55"  	,"FHQ_ACR_TAN_G55_GL"],
	["Suppressor"   ,"FHQ_ACR_TAN_G55"  	,"FHQ_ACR_TAN_G55_SD"],
	["M320 GL"   	,"FHQ_ACR_TAN_G55_SD"  	,"FHQ_ACR_TAN_G55_GL_SD"],
	["G55 Scope" 	,"FHQ_ACR_TAN_IRN_F"  	,"FHQ_ACR_TAN_G55_F"],
	["G55 Scope" 	,"FHQ_ACR_TAN_IRN_GL_F" ,"FHQ_ACR_TAN_G55_GL_F"],
	["G55 Scope" 	,"FHQ_ACR_TAN_IRN_SD_F" ,"FHQ_ACR_TAN_G55_SD_F"],
	["G55 Scope" 	,"FHQ_ACR_TAN_IRN_GL_SD_F","FHQ_ACR_TAN_G55_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_TAN_G55_F"  	,"FHQ_ACR_TAN_G55_GL_F"],
	["Suppressor"   ,"FHQ_ACR_TAN_G55_F"  	,"FHQ_ACR_TAN_G55_SD_F"],
	["M320 GL"   	,"FHQ_ACR_TAN_G55_SD_F" ,"FHQ_ACR_TAN_G55_GL_SD_F"],
	["HAMR Scope" 	,"FHQ_ACR_TAN_IRN"  	,"FHQ_ACR_TAN_HAMR"],
	["HAMR Scope" 	,"FHQ_ACR_TAN_IRN_GL"  	,"FHQ_ACR_TAN_HAMR_GL"],
	["HAMR Scope" 	,"FHQ_ACR_TAN_IRN_SD"  	,"FHQ_ACR_TAN_HAMR_SD"],
	["HAMR Scope" 	,"FHQ_ACR_TAN_IRN_GL_SD","FHQ_ACR_TAN_HAMR_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_TAN_HAMR"  	,"FHQ_ACR_TAN_HAMR_GL"],
	["Suppressor"   ,"FHQ_ACR_TAN_HAMR"  	,"FHQ_ACR_TAN_HAMR_SD"],
	["M320 GL"   	,"FHQ_ACR_TAN_HAMR_SD"  ,"FHQ_ACR_TAN_HAMR_GL_SD"],
	["HAMR Scope" 	,"FHQ_ACR_TAN_IRN_F"  	,"FHQ_ACR_TAN_HAMR_F"],
	["HAMR Scope" 	,"FHQ_ACR_TAN_IRN_GL_F" ,"FHQ_ACR_TAN_HAMR_GL_F"],
	["HAMR Scope" 	,"FHQ_ACR_TAN_IRN_SD_F" ,"FHQ_ACR_TAN_HAMR_SD_F"],
	["HAMR Scope" 	,"FHQ_ACR_TAN_IRN_GL_SD_F","FHQ_ACR_TAN_HAMR_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_TAN_HAMR_F"  	,"FHQ_ACR_TAN_HAMR_GL_F"],
	["Suppressor"   ,"FHQ_ACR_TAN_HAMR_F"  	,"FHQ_ACR_TAN_HAMR_SD_F"],
	["M320 GL"   	,"FHQ_ACR_TAN_HAMR_SD_F","FHQ_ACR_TAN_HAMR_GL_SD_F"],
	["HWS Scope" 	,"FHQ_ACR_TAN_IRN"  	,"FHQ_ACR_TAN_HWS"],
	["HWS Scope" 	,"FHQ_ACR_TAN_IRN_GL"  	,"FHQ_ACR_TAN_HWS_GL"],
	["HWS Scope" 	,"FHQ_ACR_TAN_IRN_SD"  	,"FHQ_ACR_TAN_HWS_SD"],
	["HWS Scope" 	,"FHQ_ACR_TAN_IRN_GL_SD","FHQ_ACR_TAN_HWS_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_TAN_HWS"  	,"FHQ_ACR_TAN_HWS_GL"],
	["Suppressor"   ,"FHQ_ACR_TAN_HWS"  	,"FHQ_ACR_TAN_HWS_SD"],
	["M320 GL"   	,"FHQ_ACR_TAN_HWS_SD"   ,"FHQ_ACR_TAN_HWS_GL_SD"],
	["HWS Scope" 	,"FHQ_ACR_TAN_IRN_F"  	,"FHQ_ACR_TAN_HWS_F"],
	["HWS Scope" 	,"FHQ_ACR_TAN_IRN_GL_F" ,"FHQ_ACR_TAN_HWS_GL_F"],
	["HWS Scope" 	,"FHQ_ACR_TAN_IRN_SD_F" ,"FHQ_ACR_TAN_HWS_SD_F"],
	["HWS Scope" 	,"FHQ_ACR_TAN_IRN_GL_SD_F","FHQ_ACR_TAN_HWS_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_TAN_HWS_F"  	,"FHQ_ACR_TAN_HWS_GL_F"],
	["Suppressor"   ,"FHQ_ACR_TAN_HWS_F"  	,"FHQ_ACR_TAN_HWS_SD_F"],
	["M320 GL"   	,"FHQ_ACR_TAN_HWS_SD_F" ,"FHQ_ACR_TAN_HWS_GL_SD_F"],
	["Thermal Scope","FHQ_ACR_TAN_IRN"  	,"FHQ_ACR_TAN_TWS"],
	["Thermal Scope","FHQ_ACR_TAN_IRN_GL"  	,"FHQ_ACR_TAN_TWS_GL"],
	["Thermal Scope","FHQ_ACR_TAN_IRN_SD"  	,"FHQ_ACR_TAN_TWS_SD"],
	["Thermal Scope","FHQ_ACR_TAN_IRN_GL_SD","FHQ_ACR_TAN_TWS_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_TAN_TWS"  	,"FHQ_ACR_TAN_TWS_GL"],
	["Suppressor"   ,"FHQ_ACR_TAN_TWS"  	,"FHQ_ACR_TAN_TWS_SD"],
	["M320 GL"   	,"FHQ_ACR_TAN_TWS_SD"   ,"FHQ_ACR_TAN_TWS_GL_SD"],
	["Thermal Scope","FHQ_ACR_TAN_IRN_F"  	,"FHQ_ACR_TAN_TWS_F"],
	["Thermal Scope","FHQ_ACR_TAN_IRN_GL_F" ,"FHQ_ACR_TAN_TWS_GL_F"],
	["Thermal Scope","FHQ_ACR_TAN_IRN_SD_F" ,"FHQ_ACR_TAN_TWS_SD_F"],
	["Thermal Scope","FHQ_ACR_TAN_IRN_GL_SD_F","FHQ_ACR_TAN_TWS_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_TAN_TWS_F"  	,"FHQ_ACR_TAN_TWS_GL_F"],
	["Suppressor"   ,"FHQ_ACR_TAN_TWS_F"  	,"FHQ_ACR_TAN_TWS_SD_F"],
	["M320 GL"   	,"FHQ_ACR_TAN_TWS_SD_F" ,"FHQ_ACR_TAN_TWS_GL_SD_F"],
	["M320 GL"      ,"FHQ_ACR_SNW_IRN"   	,"FHQ_ACR_SNW_IRN_GL"   ],
	["Suppressor"   ,"FHQ_ACR_SNW_IRN"   	,"FHQ_ACR_SNW_IRN_SD"   ],
	["M320 GL"   	,"FHQ_ACR_SNW_IRN_SD"  	,"FHQ_ACR_SNW_IRN_GL_SD"],	
	["M320 GL"      ,"FHQ_ACR_SNW_IRN_F"   	,"FHQ_ACR_SNW_IRN_GL_F"   ],
	["Suppressor"   ,"FHQ_ACR_SNW_IRN_F"   	,"FHQ_ACR_SNW_IRN_SD_F"   ],
	["M320 GL"   	,"FHQ_ACR_SNW_IRN_SD_F" ,"FHQ_ACR_SNW_IRN_GL_SD_F"],
	["ACOG Scope"   ,"FHQ_ACR_SNW_IRN"  	,"FHQ_ACR_SNW_RCO"],
	["ACOG Scope"   ,"FHQ_ACR_SNW_IRN_GL"  	,"FHQ_ACR_SNW_RCO_GL"],
	["ACOG Scope"   ,"FHQ_ACR_SNW_IRN_SD"  	,"FHQ_ACR_SNW_RCO_SD"],
	["ACOG Scope"   ,"FHQ_ACR_SNW_IRN_GL_SD","FHQ_ACR_SNW_RCO_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_SNW_RCO"  	,"FHQ_ACR_SNW_RCO_GL"],
	["Suppressor"   ,"FHQ_ACR_SNW_RCO"  	,"FHQ_ACR_SNW_RCO_SD"],
	["M320 GL"   	,"FHQ_ACR_SNW_RCO_SD"  	,"FHQ_ACR_SNW_RCO_GL_SD"],
	["ACOG Scope"   ,"FHQ_ACR_SNW_IRN_F"  	,"FHQ_ACR_SNW_RCO_F"],
	["ACOG Scope"   ,"FHQ_ACR_SNW_IRN_GL_F" ,"FHQ_ACR_SNW_RCO_GL_F"],
	["ACOG Scope"   ,"FHQ_ACR_SNW_IRN_SD_F" ,"FHQ_ACR_SNW_RCO_SD_F"],
	["ACOG Scope"   ,"FHQ_ACR_SNW_IRN_GL_SD_F","FHQ_ACR_SNW_RCO_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_SNW_RCO_F"  	,"FHQ_ACR_SNW_RCO_GL_F"],
	["Suppressor"   ,"FHQ_ACR_SNW_RCO_F"  	,"FHQ_ACR_SNW_RCO_SD_F"],
	["M320 GL"   	,"FHQ_ACR_SNW_RCO_SD_F" ,"FHQ_ACR_SNW_RCO_GL_SD_F"],
	["CCO Scope" ,"FHQ_ACR_SNW_IRN"  	,"FHQ_ACR_SNW_CCO"],
	["CCO Scope" ,"FHQ_ACR_SNW_IRN_GL"  	,"FHQ_ACR_SNW_CCO_GL"],
	["CCO Scope" ,"FHQ_ACR_SNW_IRN_SD"  	,"FHQ_ACR_SNW_CCO_SD"],
	["CCO Scope" ,"FHQ_ACR_SNW_IRN_GL_SD","FHQ_ACR_SNW_CCO_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_SNW_CCO"  	,"FHQ_ACR_SNW_CCO_GL"],
	["Suppressor"   ,"FHQ_ACR_SNW_CCO"  	,"FHQ_ACR_SNW_CCO_SD"],
	["M320 GL"   	,"FHQ_ACR_SNW_CCO_SD"  	,"FHQ_ACR_SNW_CCO_GL_SD"],
	["CCO Scope" ,"FHQ_ACR_SNW_IRN_F"  	,"FHQ_ACR_SNW_CCO_F"],
	["CCO Scope" ,"FHQ_ACR_SNW_IRN_GL_F" ,"FHQ_ACR_SNW_CCO_GL_F"],
	["CCO Scope" ,"FHQ_ACR_SNW_IRN_SD_F" ,"FHQ_ACR_SNW_CCO_SD_F"],
	["CCO Scope" ,"FHQ_ACR_SNW_IRN_GL_SD_F","FHQ_ACR_SNW_CCO_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_SNW_CCO_F"  	,"FHQ_ACR_SNW_CCO_GL_F"],
	["Suppressor"   ,"FHQ_ACR_SNW_CCO_F"  	,"FHQ_ACR_SNW_CCO_SD_F"],
	["M320 GL"   	,"FHQ_ACR_SNW_CCO_SD_F" ,"FHQ_ACR_SNW_CCO_GL_SD_F"],
	["G55 Scope" 	,"FHQ_ACR_SNW_IRN"  	,"FHQ_ACR_SNW_G55"],
	["G55 Scope" 	,"FHQ_ACR_SNW_IRN_GL"  	,"FHQ_ACR_SNW_G55_GL"],
	["G55 Scope" 	,"FHQ_ACR_SNW_IRN_SD"  	,"FHQ_ACR_SNW_G55_SD"],
	["G55 Scope" 	,"FHQ_ACR_SNW_IRN_GL_SD","FHQ_ACR_SNW_G55_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_SNW_G55"  	,"FHQ_ACR_SNW_G55_GL"],
	["Suppressor"   ,"FHQ_ACR_SNW_G55"  	,"FHQ_ACR_SNW_G55_SD"],
	["M320 GL"   	,"FHQ_ACR_SNW_G55_SD"  	,"FHQ_ACR_SNW_G55_GL_SD"],
	["G55 Scope" 	,"FHQ_ACR_SNW_IRN_F"  	,"FHQ_ACR_SNW_G55_F"],
	["G55 Scope" 	,"FHQ_ACR_SNW_IRN_GL_F" ,"FHQ_ACR_SNW_G55_GL_F"],
	["G55 Scope" 	,"FHQ_ACR_SNW_IRN_SD_F" ,"FHQ_ACR_SNW_G55_SD_F"],
	["G55 Scope" 	,"FHQ_ACR_SNW_IRN_GL_SD_F","FHQ_ACR_SNW_G55_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_SNW_G55_F"  	,"FHQ_ACR_SNW_G55_GL_F"],
	["Suppressor"   ,"FHQ_ACR_SNW_G55_F"  	,"FHQ_ACR_SNW_G55_SD_F"],
	["M320 GL"   	,"FHQ_ACR_SNW_G55_SD_F" ,"FHQ_ACR_SNW_G55_GL_SD_F"],
	["HAMR Scope" 	,"FHQ_ACR_SNW_IRN"  	,"FHQ_ACR_SNW_HAMR"],
	["HAMR Scope" 	,"FHQ_ACR_SNW_IRN_GL"  	,"FHQ_ACR_SNW_HAMR_GL"],
	["HAMR Scope" 	,"FHQ_ACR_SNW_IRN_SD"  	,"FHQ_ACR_SNW_HAMR_SD"],
	["HAMR Scope" 	,"FHQ_ACR_SNW_IRN_GL_SD","FHQ_ACR_SNW_HAMR_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_SNW_HAMR"  	,"FHQ_ACR_SNW_HAMR_GL"],
	["Suppressor"   ,"FHQ_ACR_SNW_HAMR"  	,"FHQ_ACR_SNW_HAMR_SD"],
	["M320 GL"   	,"FHQ_ACR_SNW_HAMR_SD"  ,"FHQ_ACR_SNW_HAMR_GL_SD"],
	["HAMR Scope" 	,"FHQ_ACR_SNW_IRN_F"  	,"FHQ_ACR_SNW_HAMR_F"],
	["HAMR Scope" 	,"FHQ_ACR_SNW_IRN_GL_F" ,"FHQ_ACR_SNW_HAMR_GL_F"],
	["HAMR Scope" 	,"FHQ_ACR_SNW_IRN_SD_F" ,"FHQ_ACR_SNW_HAMR_SD_F"],
	["HAMR Scope" 	,"FHQ_ACR_SNW_IRN_GL_SD_F","FHQ_ACR_SNW_HAMR_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_SNW_HAMR_F"  	,"FHQ_ACR_SNW_HAMR_GL_F"],
	["Suppressor"   ,"FHQ_ACR_SNW_HAMR_F"  	,"FHQ_ACR_SNW_HAMR_SD_F"],
	["M320 GL"   	,"FHQ_ACR_SNW_HAMR_SD_F","FHQ_ACR_SNW_HAMR_GL_SD_F"],
	["HWS Scope" 	,"FHQ_ACR_SNW_IRN"  	,"FHQ_ACR_SNW_HWS"],
	["HWS Scope" 	,"FHQ_ACR_SNW_IRN_GL"  	,"FHQ_ACR_SNW_HWS_GL"],
	["HWS Scope" 	,"FHQ_ACR_SNW_IRN_SD"  	,"FHQ_ACR_SNW_HWS_SD"],
	["HWS Scope" 	,"FHQ_ACR_SNW_IRN_GL_SD","FHQ_ACR_SNW_HWS_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_SNW_HWS"  	,"FHQ_ACR_SNW_HWS_GL"],
	["Suppressor"   ,"FHQ_ACR_SNW_HWS"  	,"FHQ_ACR_SNW_HWS_SD"],
	["M320 GL"   	,"FHQ_ACR_SNW_HWS_SD"   ,"FHQ_ACR_SNW_HWS_GL_SD"],
	["HWS Scope" 	,"FHQ_ACR_SNW_IRN_F"  	,"FHQ_ACR_SNW_HWS_F"],
	["HWS Scope" 	,"FHQ_ACR_SNW_IRN_GL_F" ,"FHQ_ACR_SNW_HWS_GL_F"],
	["HWS Scope" 	,"FHQ_ACR_SNW_IRN_SD_F" ,"FHQ_ACR_SNW_HWS_SD_F"],
	["HWS Scope" 	,"FHQ_ACR_SNW_IRN_GL_SD_F","FHQ_ACR_SNW_HWS_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_SNW_HWS_F"  	,"FHQ_ACR_SNW_HWS_GL_F"],
	["Suppressor"   ,"FHQ_ACR_SNW_HWS_F"  	,"FHQ_ACR_SNW_HWS_SD_F"],
	["M320 GL"   	,"FHQ_ACR_SNW_HWS_SD_F" ,"FHQ_ACR_SNW_HWS_GL_SD_F"],
	["Thermal Scope","FHQ_ACR_SNW_IRN"  	,"FHQ_ACR_SNW_TWS"],
	["Thermal Scope","FHQ_ACR_SNW_IRN_GL"  	,"FHQ_ACR_SNW_TWS_GL"],
	["Thermal Scope","FHQ_ACR_SNW_IRN_SD"  	,"FHQ_ACR_SNW_TWS_SD"],
	["Thermal Scope","FHQ_ACR_SNW_IRN_GL_SD","FHQ_ACR_SNW_TWS_GL_SD"],
	["M320 GL"   	,"FHQ_ACR_SNW_TWS"  	,"FHQ_ACR_SNW_TWS_GL"],
	["Suppressor"   ,"FHQ_ACR_SNW_TWS"  	,"FHQ_ACR_SNW_TWS_SD"],
	["M320 GL"   	,"FHQ_ACR_SNW_TWS_SD"   ,"FHQ_ACR_SNW_TWS_GL_SD"],
	["Thermal Scope","FHQ_ACR_SNW_IRN_F"  	,"FHQ_ACR_SNW_TWS_F"],
	["Thermal Scope","FHQ_ACR_SNW_IRN_GL_F" ,"FHQ_ACR_SNW_TWS_GL_F"],
	["Thermal Scope","FHQ_ACR_SNW_IRN_SD_F" ,"FHQ_ACR_SNW_TWS_SD_F"],
	["Thermal Scope","FHQ_ACR_SNW_IRN_GL_SD_F","FHQ_ACR_SNW_TWS_GL_SD_F"],
	["M320 GL"   	,"FHQ_ACR_SNW_TWS_F"  	,"FHQ_ACR_SNW_TWS_GL_F"],
	["Suppressor"   ,"FHQ_ACR_SNW_TWS_F"  	,"FHQ_ACR_SNW_TWS_SD_F"],
	["M320 GL"   	,"FHQ_ACR_SNW_TWS_SD_F" ,"FHQ_ACR_SNW_TWS_GL_SD_F"],
	["NV Scope"   	,"FHQ_MSR_DESERT"       ,"FHQ_MSR_NV_DESERT"    ],
    ["Suppressor" 	,"FHQ_MSR_NV_DESERT"    ,"FHQ_MSR_NV_SD_DESERT" ],
    ["Suppressor"   ,"FHQ_MSR_DESERT"       ,"FHQ_MSR_SD_DESERT"    ],
	["Suppressor"   ,"FHQ_RSASS_TAN"       ,"FHQ_RSASS_SD_TAN"    ],
	["NV Scope"   	,"FHQ_XM2010_DESERT"       ,"FHQ_XM2010_NV_DESERT"    ],
    ["Suppressor" 	,"FHQ_XM2010_NV_DESERT"    ,"FHQ_XM2010_NV_SD_DESERT" ],
    ["Suppressor"   ,"FHQ_XM2010_DESERT"       ,"FHQ_XM2010_SD_DESERT"    ],
	["Suppressor"   ,"vil_SV_98"       ,"vil_SV_98_SD"    ],
    ["NV Scope"     ,"FN_FAL"               ,"FN_FAL_ANPVS4"        ],
    ["Camo Paint"   ,"G36a"                 ,"G36A_camo"            ],
    ["Camo Paint"   ,"G36C"                 ,"G36C_camo"            ],
    ["Camo Paint"   ,"G36K"                 ,"G36K_camo"            ],
    ["Suppressor"   ,"G36C"                 ,"G36_C_SD_eotech"      ],
    ["Camo Paint"   ,"G36_C_SD_eotech"      ,"G36_C_SD_camo"        ],
    ["Thermal Scope","M107_DZ"              ,"m107_TWS_EP1_DZ"      ],
	["Thermal Scope","M107"              	,"m107_TWS_EP1"   		],
    ["M203 GL"      ,"M16A2"                ,"M16A2GL"              ],
    ["ACOG Scope"   ,"m16a4"                ,"m16a4_acg"            ],
    ["M203 GL"      ,"m16a4"                ,"M16A4_GL"             ],
    ["M203 GL"      ,"m16a4_acg"            ,"M16A4_ACG_GL"         ],
    ["ACOG Scope"   ,"M16A4_GL"             ,"M16A4_ACG_GL"         ],
    ["Desert Paint" ,"M24"                  ,"M24_des_EP1"          ],
    ["ACOG Scope"   ,"M240_DZ"              ,"m240_scoped_EP1_DZE"  ],
    ["ACOG Scope"   ,"M249_EP1_DZ"          ,"M249_m145_EP1_DZE"    ],
    ["Thermal Scope","M249_EP1_DZ"          ,"M249_TWS_EP1"         ],
    ["Thermal Scope","M249_EP1_DZ"          ,"M249_TWS_EP1"         ],
    ["CCO Sight"    ,"M4A1"                 ,"M4A1_Aim"             ],
    ["Camo Paint"   ,"M4A1_Aim"             ,"M4A1_Aim_camo"        ],
    ["ACOG Scope"   ,"M4A1"                 ,"M4SPR"                ],
    ["M203 GL"      ,"M4A1"                 ,"M4A1_HWS_GL"          ],
    ["ACOG Scope"   ,"M4A1_HWS_GL"          ,"M4A1_RCO_GL"          ],
    ["M203 GL"      ,"M4SPR"                ,"M4A1_RCO_GL"          ],
    ["Suppressor"   ,"M4A1_Aim_camo"        ,"M4A1_AIM_SD_camo"     ],
    ["Camo Paint"   ,"M4A1_HWS_GL"          ,"M4A1_HWS_GL_camo"     ],
    ["Suppressor"   ,"M4A1_HWS_GL_camo"     ,"M4A1_HWS_GL_SD_Camo"  ],
    ["M203 GL"      ,"m8_carbine"           ,"m8_carbineGL"         ],
    ["ACOG Scope"   ,"m8_carbine"           ,"m8_sharpshooter"      ],
    ["Thermal Scope","m8_carbine"           ,"m8_tws"               ],
    ["Suppressor"   ,"m8_tws"               ,"m8_tws_sd"            ],
    ["CCO Sight"    ,"m8_compact"           ,"m8_compact_pmc"       ],
    ["Suppressor"   ,"m8_compact_pmc"       ,"m8_holo_sd"           ],
    ["Suppressor"   ,"M9"                   ,"M9SD"                 ],
    ["Suppressor"   ,"Makarov"              ,"MakarovSD"            ],
    ["Camo Paint"   ,"MG36"                 ,"MG36_camo_Large"      ],
    ["Desert Paint" ,"MK_48_DZ"             ,"Mk_48_DES_EP1"        ],
    ["Suppressor"   ,"MP5A5"                ,"MP5SD"                ],   
	["M320 GL"   	,"RH_acr"   ,"RH_acrgl"],
	["ACOG Scope"   ,"RH_acr"   ,"RH_acracog"],
	["M320 GL"   	,"RH_acracog"   ,"RH_acrglacog"],
	["CCO Scope"    ,"RH_acr"   ,"RH_acraim"],
	["M320 GL"   	,"RH_acrbaim"   ,"RH_acrglaim"],
	["HWS Scope"    ,"RH_acr"   ,"RH_acreotech"],
	["M320 GL"   	,"RH_acreotech"   ,"RH_acrgleotech"],
	["M320 GL"   	,"RH_acrb"  ,"RH_acrbgl"],
	["ACOG Scope"   ,"RH_acrb"  ,"RH_acrbacog"],
	["M320 GL"   	,"RH_acrbacog"  ,"RH_acrbglacog"],
	["CCO Scope"    ,"RH_acr"   ,"RH_acrbaim"],
	["M320 GL"   	,"RH_acrbaim"  ,"RH_acrbglaim"],
	["CCO Scope"    ,"RH_acr"   ,"RH_acrbeotech"],
	["M320 GL"   	,"RH_acrbeotech"  ,"RH_acrbgleotech"],
	["ACOG Scope"   ,"RH_m14"   ,"RH_m14acog"],
	["CCO Scope"    ,"RH_m14"   ,"RH_m14aim"],
	["HWS Scope"    ,"RH_m14"   ,"RH_m14eot"],
	["ACOG Scope"   ,"RH_m1s"   ,"RH_m1sacog"],
	["CCO Scope"    ,"RH_m1s"   ,"RH_m1saim"],
	["HWS Scope"    ,"RH_m1s"   ,"RH_m1seot"],
	["ACOG Scope"   ,"RH_sc2"   ,"RH_sc2acog"],
	["CCO Scope"    ,"RH_sc2"   ,"RH_sc2aim"],
	["HWS Scope"    ,"RH_sc2"   ,"RH_sc2eot"],
	["M320 GL"   	,"RH_hk416"  	,"RH_hk416gl"],
	["Suppressor"   ,"RH_hk416"  	,"RH_hk416sd"],
	["M320 GL"   	,"RH_hk416sd"   ,"RH_hk416sdgl"],
	["ACOG Scope"   ,"RH_hk416"   ,"RH_hk416acog"],
	["M320 GL"   	,"RH_hk416acog"  	,"RH_hk416glacog"],
	["CCO Scope"    ,"RH_hk416"   ,"RH_hk416aim"],
	["M320 GL"   	,"RH_hk416aim"  	,"RH_hk416glaim"],
	["Suppressor"   ,"RH_hk416"  	,"RH_hk416sdaim"],
	["M320 GL"   	,"RH_hk416sdaim"  	,"RH_hk416sdglaim"],
	["HWS Scope"    ,"RH_hk416"   ,"RH_hk416eotech"],
	["M320 GL"   	,"RH_hk416eotech"  	,"RH_hk416gleotech"],
	["Suppressor"   ,"RH_hk416"  	,"RH_hk416sdeotech"],
	["M320 GL"   	,"RH_hk416sdeotech"  	,"RH_hk416sdgleotech"],
	["M320 GL"   	,"RH_hk417"  	,"RH_hk417gl"],
	["Suppressor"   ,"RH_hk417"  	,"RH_hk417sd"],
	["M320 GL"   	,"RH_hk417sd"   ,"RH_hk417sdgl"],
	["ACOG Scope"   ,"RH_hk417"   ,"RH_hk417acog"],
	["M320 GL"   	,"RH_hk417acog"  	,"RH_hk417glacog"],
	["Suppressor"   ,"RH_hk417acog"  	,"RH_hk417sdacog"],
	["M320 GL"   	,"RH_hk417sdacog"  	,"RH_hk417sglacog"],
	["CCO Scope"    ,"RH_hk417"   ,"RH_hk417aim"],
	["M320 GL"   	,"RH_hk417aim"  	,"RH_hk417glaim"],
	["Suppressor"   ,"RH_hk417aim"  	,"RH_hk417sdaim"],
	["M320 GL"   	,"RH_hk417sdaim"  	,"RH_hk417sdglaim"],
	["HWS Scope"    ,"RH_hk417"   ,"RH_hk417eotech"],
	["M320 GL"   	,"RH_hk417eotech"  	,"RH_hk417gleotech"],
	["Suppressor"   ,"RH_hk417eotech"  	,"RH_hk417sdeotech"],
	["M320 GL"   	,"RH_hk417sdeotech"  	,"RH_hk417sdgleotech"],
	["Suppressor"   ,"RH_mas"  	,"RH_massd"],
	["ACOG Scope"   ,"RH_mas"   ,"RH_masacog"],
	["Suppressor"   ,"RH_masacog"  	,"RH_massdacog"],
	["CCO Scope"    ,"RH_mas"   ,"RH_masaim"],
	["Suppressor"   ,"RH_masaim"  	,"RH_massdaim"],
	["HWS Scope"    ,"RH_mas"   ,"RH_maseotech"],
	["Suppressor"   ,"RH_maseotech"  	,"RH_massdeotech"],
	["Suppressor"   ,"RH_masb"  	,"RH_masbsd"],
	["ACOG Scope"   ,"RH_masb"   ,"RH_masbacog"],
	["Suppressor"   ,"RH_masbacog"  	,"RH_masbsdacog"],
	["CCO Scope"    ,"RH_masb"   ,"RH_masbaim"],
	["Suppressor"   ,"RH_masbaim"  	,"RH_masbsdaim"],
	["HWS Scope"    ,"RH_masb"   ,"RH_masbeotech"],
	["Suppressor"   ,"RH_masbeotech"  	,"RH_masbsdeotech"],
	["Suppressor"   ,"RH_mk22"  	,"RH_mk22sd"],
	["Suppressor"   ,"RH_mk22v"  	,"RH_mk22vsd"],
	["Suppressor"   ,"RH_usp"  	,"RH_uspsd"],
	["Suppressor"   ,"RH_m1911"  	,"RH_m1911sd"],
	["Suppressor"   ,"RH_m9"  	,"RH_m9sd"],
	["Suppressor"   ,"RH_m9c"  	,"RH_m9csd"],
    ["Gold Paint"   ,"revolver_EP1"         ,"revolver_gold_EP1"    ],  
    ["Stock"        ,"Sa58V_EP1"             ,"Sa58P_EP1"           ],
    ["ACOG Scope"   ,"Sa58V_EP1"             ,"Sa58V_RCO_EP1"       ],
    ["CCO Sight"    ,"Sa58V_EP1"             ,"Sa58V_CCO_EP1"       ],
    ["Suppressor"   ,"SCAR_H_CQC_CCO"        ,"SCAR_H_CQC_CCO_SD"   ],
    ["Suppressor"   ,"SCAR_H_LNG_Sniper"     ,"SCAR_H_LNG_Sniper_SD"],
    ["M203 GL"      ,"SCAR_L_CQC_Holo"       ,"SCAR_L_CQC_EGLM_Holo"],
    ["ACOG Scope"   ,"SCAR_L_CQC_EGLM_Holo"  ,"SCAR_L_STD_EGLM_RCO" ],
    ["Thermal Scope","SCAR_L_CQC_EGLM_Holo"  ,"SCAR_L_STD_EGLM_TWS" ],
    ["Suppressor"   ,"UZI_EP1"               ,"UZI_SD_EP1"          ],
	["Suppressor"   ,"USSR_cheytacM200"      ,"USSR_cheytacM200_sd" ],
    ["Camo Paint"   ,"SVD"                   ,"SVD_CAMO"            ],
    ["Desert Paint" ,"SVD"                   ,"SVD_des_EP1"         ],
    ["NV Scope"     ,"SVD"                   ,"SVD_NSPU_EP1"        ],
	["CCO Scope"    ,"VIL_M4"   ,"VIL_M4_aim"],
	["Suppressor"   ,"vil_9a91_c"      ,"vil_9a91_csd" ]
];
//  DZE_WEAPON_MOD_COMBINE parameters
//
//   parameter    | description                                                         |  type  | example
//  --------------|---------------------------------------------------------------------|--------|--------
//  _combined     | the name of the attachment to combine the other attachments into    | string | "CCO Sight"
//  _attachments  | array of attachments to combine into the combined attachment        | array  | ["Kobra Sight"]
//  
DZE_WEAPON_MOD_COMBINE = [
   ["G. Launcher",["M203 GL","GP25 GL","M320 GL"]],
   ["CCO Sight",["SUSAT Sight","Kobra Sight"]],
   ["ACOG Scope",["PSO Scope"]]
];
//  DZE_WEAPON_MOD_IMAGE_MAP parameters
//
//   parameter    | description                                                         |  type  | example
//  --------------|---------------------------------------------------------------------|--------|--------
//  _weaponMod    | the name of the attachment which will use the image                 | string | "Suppressor"
//  _imageClass   | the class name of which the image will be used for the attachment   | string | "64Rnd_9x19_SD_Bizon"
//
DZE_WEAPON_MOD_IMAGE_MAP = [
    ["Suppressor","64Rnd_9x19_SD_Bizon"],
    ["G. Launcher","1Rnd_HE_M203"],
    ["CCO Sight","Binocular"],
    ["ACOG Scope","Binocular_Vector"],
	["G55 Scope","Binocular_Vector"],
	["HAMR Scope","Binocular_Vector"],
	["HWS Scope","Binocular_Vector"],
    ["Thermal Scope","LaserDesignator"],
    ["NV Scope","NVGoggles"],
    ["Stock","ItemCore"],
    ["Camo Paint","ItemCanvas"],
	["Winter Paint","ItemCanvas"],
    ["Desert Paint","ItemBurlap"],
    ["Gold Paint","ItemGoldBar"]
];

//##### SUICIDE CONFIGURATION ####################################################################################################################################################################
//  DZE_SUICIDE_ADDON_ENABLE -- If true, suicide addon is enabled. If false, suicide addon is disabled. REQUIRES DZE_CLICK_ACTIONS_ENABLE = true;
DZE_SUICIDE_ADDON_ENABLE = true;
//  DZE_SUICIDE_GUNS = [_weaponClass1,_weaponClass2, ...more...];
DZE_SUICIDE_GUNS = ["M9","M9SD","Makarov","MakarovSD","Sa61_EP1","UZI_EP1","UZI_SD_EP1","revolver_EP1","revolver_gold_EP1","glock17_EP1","Colt1911"];
//  DZE_SUICIDE_GENERIC = [_weaponClass1,_weaponClass2, ...more...];
DZE_SUICIDE_GENERIC = ["ItemKnife","ItemHatchet_DZE","ItemCrowbar"];
//  DZE_SUICIDE_ADDON_ENABLE -- If true, you must have at least one bullet to commit suicide. If false, you can kill yourself without a bullet.
DZE_SUICIDE_REQUIRE_BULLET = true;
//  DZE_SUICIDE_CANCEL_TIME -- positive number which determines how long a player has to cancel the suicide action before they actually begin killing themselves
DZE_SUICIDE_CANCEL_TIME = 5;

//##### CLOTHES CONFIGURATION ####################################################################################################################################################################
//  DZE_TAKECLOTHES_ADDON_ENABLE -- If true, take clothes addon is enabled. If false, take clothes addon is disabled.
DZE_TAKECLOTHES_ADDON_ENABLE = true;
//  DZE_TAKECLOTHES_MAP parameters
//
//   parameter    | description                                                         |  type  | example
//  --------------|---------------------------------------------------------------------|--------|--------
//  _model        | the name of the model of the dead player/zombie/ai/etc              | string | "z_policeman"
//  _skinPackage  | the class name of the skin which should be given for that model     | string | "Skin_RU_Policeman_DZ"
//
DZE_TAKECLOTHES_MAP = [
    ["z_policeman","Skin_RU_Policeman_DZ"],
    ["z_suit1","Skin_Functionary1_EP1_DZ"],
    ["z_suit2","Skin_Functionary1_EP1_DZ"],
    ["z_suit3","Skin_Functionary1_EP1_DZ"], 
    ["z_priest","Skin_Priest_DZ"],
    ["z_soldier","Skin_Camo1_DZ"],
    ["z_soldier_heavy","Skin_Soldier1_DZ"],
    ["z_soldier_pilot","Skin_RU_Soldier_Crew_DZ"]
];

//##### KITS CONFIGURATION ####################################################################################################################################################################
//  DZE_KITS_ADDON_ENABLE -- If true, kit addon is enabled. If false, kit addon is disabled. REQUIRES DZE_CLICK_ACTIONS_ENABLE = true;
DZE_KITS_ADDON_ENABLE = true;
//  DZE_KIT_CONFIG parameters
//
//   parameter    | description                                                          |  type  | example
//  --------------|----------------------------------------------------------------------|--------|--------
//  _name         | the name of the kit which is displayed on right clicking a vault     | string | "Donator Kit #1"
//  _contents     | array in the format of [[_amount,_item],[_amount,_item],[...more..]] | string | [[2,"PartGeneric"],[9,"30m_plot_kit"]]
//
DZE_KITS_CONFIG = [
    ["Donator Kit #1",[[5,"ItemToolbox"],[2,"30m_plot_kit"]]],
    ["Donator Kit #2",[[2,"PartGeneric"],[9,"30m_plot_kit"]]]
];
DZE_KITS_ADMINS = ["76561198173462307"];

//##### MAPS CONFIGURATION ####################################################################################################################################################################
//  DZE_MAP_MARKER_ADDON_ENABLE -- If true, map marker addon is enabled. If false, map marker addon is disabled. REQUIRES DZE_CLICK_ACTIONS_ENABLE = true;
DZE_MAP_MARKER_ADDON_ENABLE = true;
// DZE_MAP_MARKER_ALLOW_SELF -- if true, players can use GPS or Map to mark themselves on the map
DZE_MAP_MARKER_ALLOW_SELF = true;
// DZE_MAP_MARKER_ALLOW_FRIENDLIES -- if true, players can use GPS or Map to mark friendlies on the map
DZE_MAP_MARKER_ALLOW_FRIENDLIES = true;
// DZE_MAP_MARKER_ALLOW_VEHICLES -- if true, players can use GPS or Map to mark owned vehicles on the map
DZE_MAP_MARKER_ALLOW_VEHICLES = true;
// DZE_MAP_MARKER_ALLOW_ZOMBIES -- if true, players can use GPS or Map to mark Zombie on the map
DZE_MAP_MARKER_ALLOW_ZOMBIES = true;
// DZE_MAP_MARKER_VEHICLE_KEY_ONLY -- Only show vehicles that you have a key for? Only works if DZE_MAP_MARKER_ALLOW_VEHICLES = true;
DZE_MAP_MARKER_VEHICLE_KEY_ONLY = true;
// DZE_MAP_MARKER_ZOMBIE_RANGE -- Zombie Radar Radius. Only works if DZE_MAP_MARKER_ALLOW_ZOMBIES = true;
DZE_MAP_MARKER_ZOMBIE_RANGE = 100;
// DZE_MAP_MARKER_VEHICLE_RANGE -- Vehicle Radar Radius. Only works if DZE_MAP_MARKER_ALLOW_VEHICLES = true;
DZE_MAP_MARKER_VEHICLE_RANGE = 5000;
// DZE_MAP_MARKER_FRIENDLY_RANGE -- Friendly Radar Radius. Only works if DZE_MAP_MARKER_ALLOW_FRIENDLY = true;
DZE_MAP_MARKER_FRIENDLY_RANGE = 5000;
// DZE_BASE_JUMP_ADDON_ENABLE -- if true, players can use high locations to base jump
DZE_BASE_JUMP_ADDON_ENABLE = true;